<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.9.RELEASE</version>
	</parent>
	<groupId>no.nav.dokarkiv</groupId>
	<artifactId>dokarkiv</artifactId>
	<version>1-SNAPSHOT</version>

	<packaging>pom</packaging>
	<name>dokarkiv</name>

	<modules>
		<module>app</module>
		<module>core</module>
		<module>dokumentproduksjoninfo</module>
		<module>arkiverdokumentproduksjon</module>
		<module>arkiverdokumentmottak</module>
		<module>behandlejournal</module>
		<module>innsynjournal</module>
		<module>inngaaendejournal</module>
		<module>behandleinngaaendejournal</module>
		<module>journal</module>
		<module>journalfoerinngaaende</module>
		<module>hentdokument</module>
		<module>hentjournalsakinfo</module>
		<module>arkivervariant</module>
		<module>admin</module>
		<module>journalpost</module>
	</modules>

	<properties>
		<project.scm.id>stash</project.scm.id>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>11</java.version>
		<javax.inject.version>1</javax.inject.version>
		<jakarta.jaxws-api.version>2.3.2</jakarta.jaxws-api.version>
		<jakarta.jws-api.version>1.1.1</jakarta.jws-api.version>
		<jakarta.activation.version>1.2.1</jakarta.activation.version>
		<saaj-impl.version>1.5.1</saaj-impl.version>
		<oracle.version>12.2.0.1</oracle.version>
		<cxf.version>3.4.0</cxf.version>
		<!-- Flyway versjon må ses i sammenheng med joark og Flyway42AutoConfiguration -->
		<flyway.version>4.2.0</flyway.version>
		<simpleflatmapper.version>8.2.1</simpleflatmapper.version>
		<swagger.version>2.9.2</swagger.version>
		<commons-collections4.version>4.4</commons-collections4.version>
		<logstash-logback-encoder.version>6.4</logstash-logback-encoder.version>
		<logback-syslog4j.version>1.0.0</logback-syslog4j.version>
		<jaxb2-basics-runtime.version>0.6.4</jaxb2-basics-runtime.version>
		<java-jwt.version>3.10.3</java-jwt.version>
		<aws-java-sdk-s3.version>1.11.848</aws-java-sdk-s3.version>
		<modig-security.version>3.0.6</modig-security.version>
		<abac-spring.version>1.6.0</abac-spring.version>
		<freg-security.version>3.8.1-FIX</freg-security.version>
		<commons.beanutils.version>1.9.4</commons.beanutils.version>
		<commons.io.version>2.7</commons.io.version>
		<swagger-ui.version>3.9.2</swagger-ui.version>
		<argLine>-Xmx1024m</argLine>
		<lombok.version>1.18.12</lombok.version>
		<!-- test -->
		<modig.testcertificates.version>1.2.5</modig.testcertificates.version>
		<spring-cloud-contract-wiremock.version>2.1.5.RELEASE</spring-cloud-contract-wiremock.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>app</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>core</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>core</artifactId>
				<version>1-SNAPSHOT</version>
				<type>test-jar</type>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>dokumentproduksjoninfo</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>arkiverdokumentproduksjon</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>arkiverdokumentmottak</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>behandlejournal</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>innsynjournal</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>inngaaendejournal</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>behandleinngaaendejournal</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>journalfoerinngaaende</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>journal</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>hentdokument</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>hentjournalsakinfo</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>arkivervariant</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>admin</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokarkiv</groupId>
				<artifactId>journalpost</artifactId>
				<version>1-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>com.oracle</groupId>
				<artifactId>ojdbc8</artifactId>
				<version>${oracle.version}</version>
			</dependency>
			<dependency>
				<groupId>com.oracle</groupId>
				<artifactId>ucp</artifactId>
				<version>${oracle.version}</version>
			</dependency>
			<dependency>
				<groupId>org.simpleflatmapper</groupId>
				<artifactId>sfm-springjdbc</artifactId>
				<version>${simpleflatmapper.version}</version>
			</dependency>
			<dependency>
				<groupId>javax.inject</groupId>
				<artifactId>javax.inject</artifactId>
				<version>${javax.inject.version}</version>
			</dependency>
			<dependency>
				<groupId>jakarta.xml.ws</groupId>
				<artifactId>jakarta.xml.ws-api</artifactId>
				<version>${jakarta.jaxws-api.version}</version>
			</dependency>
			<dependency>
				<groupId>jakarta.jws</groupId>
				<artifactId>jakarta.jws-api</artifactId>
				<version>${jakarta.jws-api.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sun.activation</groupId>
				<artifactId>jakarta.activation</artifactId>
				<version>${jakarta.activation.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.messaging.saaj</groupId>
				<artifactId>saaj-impl</artifactId>
				<version>${saaj-impl.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-spring-boot-starter-jaxws</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-ws-security</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-collections4</artifactId>
				<version>${commons-collections4.version}</version>
			</dependency>
			<dependency>
				<groupId>net.logstash.logback</groupId>
				<artifactId>logstash-logback-encoder</artifactId>
				<version>${logstash-logback-encoder.version}</version>
			</dependency>
			<dependency>
				<groupId>com.papertrailapp</groupId>
				<artifactId>logback-syslog4j</artifactId>
				<version>${logback-syslog4j.version}</version>
			</dependency>
			<dependency>
				<groupId>org.jvnet.jaxb2_commons</groupId>
				<artifactId>jaxb2-basics-runtime</artifactId>
				<version>${jaxb2-basics-runtime.version}</version>
			</dependency>
			<dependency>
				<groupId>com.auth0</groupId>
				<artifactId>java-jwt</artifactId>
				<version>${java-jwt.version}</version>
			</dependency>
			<dependency>
				<groupId>com.amazonaws</groupId>
				<artifactId>aws-java-sdk-s3</artifactId>
				<version>${aws-java-sdk-s3.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.modig</groupId>
				<artifactId>modig-security-authorization</artifactId>
				<version>${modig-security.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.freg</groupId>
				<artifactId>abac-spring</artifactId>
				<version>${abac-spring.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.freg</groupId>
				<artifactId>freg-security-oidc</artifactId>
				<version>${freg-security.version}</version>
			</dependency>
			<dependency>
				<groupId>commons-io</groupId>
				<artifactId>commons-io</artifactId>
				<version>${commons.io.version}</version>
				<scope>runtime</scope>
			</dependency>
			<dependency>
				<groupId>commons-beanutils</groupId>
				<artifactId>commons-beanutils</artifactId>
				<version>${commons.beanutils.version}</version>
			</dependency>
			<dependency>
				<groupId>org.webjars</groupId>
				<artifactId>swagger-ui</artifactId>
				<version>${swagger-ui.version}</version>
			</dependency>
			<!-- provided og test -->
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-wiremock</artifactId>
				<version>${spring-cloud-contract-wiremock.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<artifactId>freg-security-test-oidc-tools</artifactId>
				<groupId>no.nav.freg</groupId>
				<version>${freg-security.version}</version>
				<scope>test</scope>
			</dependency>

			<!--Swagger-->
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>${swagger.version}</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>${swagger.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.modig</groupId>
				<artifactId>modig-testcertificates</artifactId>
				<version>${modig.testcertificates.version}</version>
				<scope>test</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
			<resource>
				<directory>src/main/resources/data</directory>
				<filtering>false</filtering>
			</resource>
		</resources>
		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-webdav-jackrabbit</artifactId>
				<version>1.0</version>
			</extension>
		</extensions>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M3</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>3.0.0-M3</version>
			</plugin>
			<plugin>
				<artifactId>maven-toolchains-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<goals>
							<goal>toolchain</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<toolchains>
						<jdk>
							<version>11</version>
							<vendor>openjdk</vendor>
						</jdk>
					</toolchains>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>