spring.profiles.include=nais
app.name="dokdistkanal"

logging.config=classpath:logback-local.xml

AKTOERV2.URL=https://app-t3.adeo.no/aktoerid/AktoerService/v2
ABAC.URL=https://wasapp-t3.adeo.no/asm-pdp/authorize
securityTokenService.url=https://sts-t3.test.local/SecurityTokenServiceProvider/
serviceuser.username=dummy
serviceuser.***passord=gammelt_passord***
ldap.navuser.basedn=ou=NAV,ou=BusinessUnits,dc=test,dc=local
ldap.serviceuser.basedn=ou=ServiceAccounts,dc=test,dc=local
dokarkiv.hentdokument.baseurl=http://localhost/hentdokument
joark.hentdokument.baseurl=http://hentdokumentnoop

spring.datasource.url=jdbc:oracle:thin:@d26dbfl022.test.local:1521/joark_u1
spring.datasource.username=dummy
spring.datasource.***passord=gammelt_passord***

# flyway
spring.flyway.enabled=true
spring.flyway.table=schema_version
spring.flyway.out-of-order=false
spring.flyway.validate-on-migrate=false