<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>dokarkiv</artifactId>
		<groupId>no.nav.dokarkiv</groupId>
		<version>1-SNAPSHOT</version>
	</parent>

	<artifactId>app</artifactId>

	<dependencies>
		<!-- domenetjenester -->
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>dokumentproduksjoninfo</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>arkiverdokumentproduksjon</artifactId>
		</dependency>

		<!-- virksomhetstjenester -->
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>hentjournalsakinfo</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>admin</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>arkivervariant</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>journalpost</artifactId>
		</dependency>

		<!-- annet -->
		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
		</dependency>
		<dependency>
			<groupId>com.papertrailapp</groupId>
			<artifactId>logback-syslog4j</artifactId>
		</dependency>

		<!-- Test -->
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>core</artifactId>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<finalName>app</finalName>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>