<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>dokarkiv</artifactId>
		<groupId>no.nav.dokarkiv</groupId>
		<version>1-SNAPSHOT</version>
	</parent>

	<artifactId>app</artifactId>
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-core</artifactId>
			<version>${flyway.version}</version>
		</dependency>
		<!-- domenetjenester -->
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>dokumentproduksjoninfo</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>arkiverdokumentproduksjon</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>arkiverdokumentmottak</artifactId>
		</dependency>
		<!-- virksomhetstjenester -->
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>behandlejournal</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>innsynjournal</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>inngaaendejournal</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>behandleinngaaendejournal</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>journal</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>hentdokument</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>hentjournalinfo</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>hentjournalsakinfo</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>journalfoerinngaaende</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>logiskslettdokument</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>fysiskslettdokument</artifactId>
		</dependency>
		<!-- annet -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>5.1</version>
		</dependency>
		<dependency>
			<groupId>com.papertrailapp</groupId>
			<artifactId>logback-syslog4j</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>core</artifactId>
			<version>1-SNAPSHOT</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<finalName>app</finalName>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>