package no.nav.dokarkiv.hentjournalsakinfo.common;

import lombok.experimental.UtilityClass;

@UtilityClass
public final class SqlProjections {
	public static final String RELEVANTE_DATA =
			"""
					j.journalpost_id                AS journalpostid,
					j.innhold                       AS innhold,
					j.k_fagomrade                   AS fagomrade,
					j.k_behandlingstema             AS behandlingstema,
					bt.dekode                       AS behandlingstemanavn,
					j.k_journal_s                   AS journalstatus,
					j.avsend_mottak_id              AS avsendermottakerid,
					j.k_avsend_mottak_id_t          AS avsendermottakeridtype,
					j.avsend_mottaker               AS avsendermottakernavn,
					j.land                          AS avsendermottakerland,
					j.journalf_enhet                AS journalforendeenhet,
					j.journalfort_av_navn           AS journalfortavnavn,
					j.opprettet_av_navn             AS opprettetavnavn,
					j.k_mottaks_kanal               AS mottakskanal,
					j.k_utsendings_kanal            AS utsendingskanal,
					j.k_journalpost_t               AS journalposttype,
					j.dato_opprettet                AS datoopprettet,
					j.dato_ekspedert                AS ekspedertdato,
					j.dato_mottatt                  AS mottattdato,
					j.dato_journal                  AS journaldato,
					j.dato_dokument                 AS dokumentdato,
					j.dato_avs_retur                AS avsreturdato,
					j.dato_sendt_print              AS sendtprintdato,
					j.dato_lest                     AS lestdato,
					j.k_skjerming_type              AS skjerming,
					j.antall_retur                  AS antallretur,
					j.kanal_referanse_id            AS kanalreferanseid,
					j.k_innsyn                      AS innsyn,
					s.sak_nr_fk                     AS saksrelasjon_sakid,
					s.feilregistrert                AS saksrelasjon_feilregistrert,
					s.k_fagsystem                   AS saksrelasjon_fagsystem,
					sa.aktoerid                     AS saksrelasjon_aktoerid,
					sa.tema                         AS saksrelasjon_tema,
					sa.fagsaknr                     AS saksrelasjon_fagsaknr,
					sa.orgnr                        AS saksrelasjon_orgnr,
					sa.applikasjon                  AS saksrelasjon_applikasjon,
					sa.opprettet_tidspunkt          AS saksrelasjon_opprettet_tid,
					sa.opprettet_av                 AS saksrelasjon_opprettet_av,
					b.bruker_id                     AS bruker_brukerid,
					b.k_bruker_t                    AS bruker_brukeridtype,
					t.nokkel                        AS tilleggsopplysninger_nokkel,
					t.verdi                         AS tilleggsopplysninger_verdi,
					d.dokument_info_id              AS dokumenter_dokumentinfoid,
					rel.k_tilkn_jp_som              AS dokumenter_tilknyttetsom,
					rel.jp_dok_info_rel_id          AS dokumenter_jprelasjonid,
					d.k_dokument_s                  AS dokumenter_dokumentstatus,
					d.dato_dok_ferdig               AS dokumenter_datoferdigstilt,
					d.brev_kode                     AS dokumenter_brevkode,
					d.dokumenttype_id               AS dokumenter_dokumenttypeid,
					d.tittel                        AS dokumenter_tittel,
					d.kassert                       AS dokumenter_kassert,
					d.k_kategori_t                  AS dokumenter_kategori,
					d.innskr_partsinnsyn            AS dokumenter_innskrpartsinnsyn,
					d.innskr_partsinnsyn_tredjepart AS dokumenter_innskrtredjepart,
					d.organ_internt                 AS dokumenter_organinternt,
					rel.k_skjerming_type            AS dokumenter_skjerming,
					d.orig_journalpost_id           AS dokumenter_origjournalpostid,
					fd.k_skjerming_type             AS dokumenter_varianter_skjerming,
					fd.k_variant_format             AS dokumenter_varianter_variantf,
					fd.fil_navn                     AS dokumenter_varianter_filnavn,
					fd.fil_uuid                     AS dokumenter_varianter_filuuid,
					fd.k_fil_t                      AS dokumenter_varianter_filtype,
					fd.fil_storrelse                AS dokumenter_varianter_filstorrelse,
					tsi.skannet_innhold_id          AS dokumenter_logiske_vedleggid,
					tsi.vedlegg_innhold             AS dokumenter_logiske_tittel""";


	public static final String UTSENDINGSINFO_DATA = """
   					,
   					ut.adresselinje1                AS utsendingsInfo_fysiskPostadresse_adresselinje1,
					ut.adresselinje2                AS utsendingsInfo_fysiskPostadresse_adresselinje2,
					ut.adresselinje3                AS utsendingsInfo_fysiskPostadresse_adresselinje3,
					ut.postnummer					AS utsendingsInfo_fysiskPostadresse_postnummer,
					ut.poststed						AS utsendingsInfo_fysiskPostadresse_poststed,
					ut.landkode						AS utsendingsInfo_fysiskPostadresse_landkode,
					ut.digitalpostkasseadresse      AS utsendingsInfo_digitalPostadresse_digitalpostkasseadresse,
					ut.digitalpostkasseleverandor   AS utsendingsInfo_digitalPostadresse_postkasseLeverandor,
					ut.digital_kontaktinformasjon	AS utsendingsInfo_navNoVarsling_varselSendtTil,
					ut.varslingstekst				AS utsendingsInfo_navNoVarsling_varseltekst""";

}
