-- Opprett tabell siden dette ikke er en egen JPA entitet
create table T_JP_TILLEGG (
  JOURNALPOST_ID NUMBER(11,0) NOT NULL,
  NOKKEL VARCHAR2(20 CHAR) NOT NULL,
  VERDI VARCHAR2(100 CHAR) NOT NULL
);

ALTER TABLE T_JP_TILLEGG
  ADD CONSTRAINT XPKT_JP_TILLEGG PRIMARY KEY ("JOURNALPOST_ID", "NOKKEL");

ALTER TABLE T_JP_TILLEGG
  ADD CONSTRAINT XPKT_JP_TILLEGG_UNIQE UNIQUE ("NOKKEL", "VERDI");
