<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<artifactId>dokarkiv</artifactId>
		<groupId>no.nav.dokarkiv</groupId>
		<version>1-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<artifactId>arkiverdokumentproduksjon</artifactId>

	<properties>
		<arkiverdokumentproduksjon-tjenestespesifikasjon.version>3.2.1-SNAPSHOT
		</arkiverdokumentproduksjon-tjenestespesifikasjon.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>core</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.tjenester.brevogarkiv</groupId>
			<artifactId>arkiverdokumentproduksjon-tjenestespesifikasjon</artifactId>
			<version>${arkiverdokumentproduksjon-tjenestespesifikasjon.version}</version>
			<classifier>jaxws</classifier>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>RELEASE</version>
		</dependency>
		<dependency>
			<groupId>no.nav.dokarkiv</groupId>
			<artifactId>core</artifactId>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

</project>