kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{APP_NAME}}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  filesFrom:
    - secret: {{ DOKARKIV_SECRET }}
      mountPath: /var/run/secrets/nais_secrets
  envFrom:
    - secret: {{ DOKARKIV_SECRET }}
    - secret: ldap
  env:
    - name: JAVA_TRUSTSTORE_OPTIONS
      value: "-Djavax.net.ssl.trustStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.trustStorePassword=$(NAV_TRUSTSTORE_PASSWORD)"
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=75
              -Dio.netty.allocator.type=pooled
              $(JAVA_PROXY_OPTIONS) $(JAVA_TRUSTSTORE_OPTIONS)"
    - name: NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE }}
    - name: LDAP_NAVUSER_BASEDN
      value: {{ LDAP_NAVUSER_BASEDN }}
    - name: LDAP_SERVICEUSER_BASEDN
      value: {{ LDAP_SERVICEUSER_BASEDN }}
    - name: LDAP_DOMAIN
      value: {{ LDAP_DOMAIN }}
    - name: LDAP_BASEDN
      value: {{ LDAP_BASEDN }}
    - name: DOKARKIV_ENDPOINTS_PDL_URL
      value: {{ DOKARKIV_ENDPOINTS_PDL_URL }}
    - name: DOKARKIV_ENDPOINTS_SAF_URL
      value: {{ DOKARKIV_ENDPOINTS_SAF_URL }}
    - name: DOKARKIV_ENDPOINTS_SAF_SCOPE
      value: {{ DOKARKIV_ENDPOINTS_SAF_SCOPE }}
    - name: DOKARKIV_DATABASE_POOLSIZE
      value: "{{ DOKARKIV_DATABASE_POOLSIZE }}"
    - name: DOKARKIV_DATABASE_PARALLEL_HINT_SUPPORT
      value: "{{ DOKARKIV_DATABASE_PARALLEL_HINT_SUPPORT }}"
    - name: DOKARKIV_EREG_URL
      value: {{ DOKARKIV_EREG_URL }}
    - name: DOKPRODMELLOMLAGER_PROJECTID
      value: {{ DOKPRODMELLOMLAGER_PROJECTID }}
    - name: DOKPRODMELLOMLAGER_BUCKET
      value: {{ DOKPRODMELLOMLAGER_BUCKET }}
    - name: DOKPRODMELLOMLAGER_KEYRING
      value: {{ DOKPRODMELLOMLAGER_KEYRING }}
    - name: DOKPRODMELLOMLAGER_KEYID
      value: {{ DOKPRODMELLOMLAGER_KEYID }}
    - name: SPRINGDOC_ENABLED
      value: "{{ SPRINGDOC_ENABLED }}"
    - name: DOKARKIV_SKJERMDOKUMENT_TILLATTEHJEMLER
      value: "{{ DOKARKIV_SKJERMDOKUMENT_TILLATTEHJEMLER }}"
    - name: DOKARKIV_JOARK_VEDLIKEHOLD_GROUP_ID
      value: {{ JOARK_VEDLIKEHOLD_GROUP_ID }}
    - name: DOKARKIV_ENDPOINTS_PDL_SCOPE
      value: {{ DOKARKIV_ENDPOINTS_PDL_SCOPE }}
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name={{ ENVIRONMENT }}"
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/run/secrets/nais_secrets/gcloud_serviceaccount.json"
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
    - {{this }}
    {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 15
    periodSeconds: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 6500Mi
    requests:
      cpu: 100m
      memory: 4400Mi
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          - id: "{{ JOARK_VEDLIKEHOLD_GROUP_ID }}"
  accessPolicy:
    inbound:
      rules:
    {{#each AZURE_IAC_RULES}}
        - application: {{app}}
          namespace: {{namespace}}
          cluster: {{cluster}}
          permissions:
            {{#if roles}}
            roles:
              {{#each roles}}
              - "{{this}}"
              {{/each}}
            {{/if}}
            {{#if scopes}}
            scopes:
              {{#each scopes}}
              - "{{this}}"
              {{/each}}
            {{/if}}
    {{/each}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
