kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{APP_NAME}}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  env:
    - name: NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL }}
    {{#if NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_ACCEPTED_AUDIENCE}}
    - name: NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_ACCEPTED_AUDIENCE }}
    {{/if}}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE }}
    - name: SPRING_DATASOURCE_URL
      value: {{ SPRING_DATASOURCE_URL }}
    - name: SPRING_LDAP_URLS
      value: {{ SPRING_LDAP_URLS }}
    - name: LDAP_NAVUSER_BASEDN
      value: {{ LDAP_NAVUSER_BASEDN }}
    - name: LDAP_SERVICEUSER_BASEDN
      value: {{ LDAP_SERVICEUSER_BASEDN }}
    - name: LDAP_DOMAIN
      value: {{ LDAP_DOMAIN }}
    - name: LDAP_BASEDN
      value: {{ LDAP_BASEDN }}
    - name: DOKARKIV_ENDPOINTS_PDL_URL
      value: {{ DOKARKIV_ENDPOINTS_PDL_URL }}
    - name: DOKARKIV_ENDPOINTS_SAF_URL
      value: {{ DOKARKIV_ENDPOINTS_SAF_URL }}
    - name: DOKARKIV_ENDPOINTS_SAF_SCOPE
      value: {{ DOKARKIV_ENDPOINTS_SAF_SCOPE }}
    - name: APPD_NAME
      value: {{ APPD_NAME }}
    - name: DOKARKIV_DATABASE_POOLSIZE
      value: "{{ DOKARKIV_DATABASE_POOLSIZE }}"
    - name: DOKPRODMELLOMLAGER_PROJECTID
      value: {{ DOKPRODMELLOMLAGER_PROJECTID }}
    - name: DOKPRODMELLOMLAGER_BUCKET
      value: {{ DOKPRODMELLOMLAGER_BUCKET }}
    - name: DOKPRODMELLOMLAGER_KEYRING
      value: {{ DOKPRODMELLOMLAGER_KEYRING }}
    - name: DOKPRODMELLOMLAGER_KEYID
      value: {{ DOKPRODMELLOMLAGER_KEYID }}
    - name: SPRINGDOC_ENABLED
      value: "{{ SPRINGDOC_ENABLED }}"
    - name: AZURE_AD_ADMIN_ROLE
      value: {{ AZURE_AD_ADMIN_ROLE }}
    - name: DOKARKIV_ENDPOINTS_PDL_SCOPE
      value: {{ DOKARKIV_ENDPOINTS_PDL_SCOPE }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
    - {{this }}
    {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 15
    periodSeconds: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 4096Mi
    requests:
      memory: 3584Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ DOKARKIV_DS }}
        mountPath: "/var/run/secrets/nais.io/dokarkivDS"
      - kvPath: {{ SRVDOKARKIV }}
        mountPath: "/secrets/serviceuser/srvdokarkiv"
      - kvPath: {{ DOKARKIV_VAULT }}
        mountPath: "/var/run/secrets/nais.io/vault"
      - kvPath: {{ SRV_LINUX }}
        mountPath: "/var/run/secrets/nais.io/ldap"
      - kvPath: {{ APPDYNAMICS }}
        mountPath: "/var/run/secrets/nais.io/appdynamics"
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
{{#if AZURE_IAC_RULES}}
  accessPolicy:
    inbound:
      rules:
    {{#each AZURE_IAC_RULES}}
        - application: {{app}}
          namespace: {{namespace}}
          cluster: {{cluster}}
          permissions:
            {{#if roles}}
            roles:
              {{#each roles}}
              - "{{this}}"
              {{/each}}
            {{/if}}
            {{#if scopes}}
            scopes:
              {{#each scopes}}
              - "{{this}}"
              {{/each}}
            {{/if}}
    {{/each}}
{{/if}}