spring.main.banner-mode=off
logging.config=classpath:logback-nais.xml

spring.datasource.driver-class-name=oracle.jdbc.pool.OracleDataSource
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.session_factory.interceptor=no.nav.dokarkiv.core.domain.interceptor.PersistentDomainObjectHibernateInterceptor
