spring.main.banner-mode=off
# server
server.tomcat.threads.min-spare=50
server.tomcat.threads.max=100
server.error.include-message=always
# server graceful shutdown
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
# actuators
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
# database
spring.datasource.driver-class-name=oracle.jdbc.pool.OracleDataSource
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.session_factory.interceptor=no.nav.dokarkiv.core.domain.interceptor.PersistentDomainObjectHibernateInterceptor
spring.transaction.default-timeout=300s
spring.jackson.deserialization.fail-on-unknown-properties=true
#
# application configuration
#
behandlejournal.v2.lagreVedleggPaaJournalpost.vedleggDokumentTypeId=458212
behandlejournal.v3.lagreVedleggPaaJournalpost.vedleggDokumentTypeId=458212
innsynjournal.v2.innsyn.earliest.date=2016-06-04
journal.v3.predefinert.antall.saker=50
hentdokument.dokumenturl.urlTimeToLiveMinutes=1
hentdokument.dlf.metadataXmlEncoding=ISO-8859-1
hentdokument.dlf.vedleggUrlTimeToLiveMinutes=480
hentdokument.dlf.vedleggNonSslUrl=true
auth.group.lesetilgang.joark=CN=0000-GA-joark-les,OU=AccountGroupNotInRemedy,OU=Groups,OU=NAV,OU=BusinessUnits
#
# flyway
#
spring.flyway.enabled=true
spring.flyway.table=schema_version
spring.flyway.out-of-order=false
spring.flyway.validate-on-migrate=false
# freg security
freg.security.oidc.auth.securedPath=/rest/**
freg.security.oidc.auth.ignoredPaths=/rest/intern/**
freg.security.oidc.auth.enabled=true
freg.security.oidc.auth.idToken.header-enabled=true
freg.security.oidc.auth.idToken.validation.type=basic
graphiql.enabled=true
graphiql.endpoint=/mock/graphql

# NAIS cluster endpoints
storage_s3_url=http://objectstore.rook-ceph

spring.jackson.mapper.accept-case-insensitive-properties=true
