package no.nav.dokarkiv.core.domain.codes;

/**
 * @author Ugur Alpay Cenar, Visma Consulting.
 */
public enum AksjonsTypeCode {

	ARKIVERING,
	AVBRYT,
	EKSPEDER,
	ENDRE_METADATA,
	ENDRE_SKJERMING,
	FEILREGISTRER_SAKSTILKNYTNING,
	FERDIGSTILL,
	KASSERING,
	KOPIER_JOURNALPOST,
	OPPHEV_FEILREGISTRERING,
	OVERSTYR_INNSYN,
	OPPRETT,
	SAKSTILKNYTNING,
	SLETTING,
	UKJENT_BRUKER,
	UTGAAR
}
