package no.nav.dokarkiv.core.domain.codes;

public enum AksjonsTypeCode {
	ARKIVERING,
	AVBRYT,
	EKSPEDER,
	ENDRE_METADATA,
	ENDRE_SKJERMING,
	ENDRE_JOURNALPOSTTYPE,
	FEILREGISTRER_SAKSTILKNYTNING,
	FERDIGSTILL,
	KASSERING,
	KOPIER_JOURNALPOST,
	OPPHEV_FEILREGISTRERING,
	OVERSTYR_INNSYN,
	OPPRETT,
	SAKSTILKNYTNING,
	SLETTING,
	UKJENT_BRUKER,
	UTGAAR,
	TILKNYTT_NYTT_DOKUMENT
}
