package no.nav.dokarkiv.core.domain.codes;

//Obs! Nye verdier her må også legges til i tabellen t_k_aksjon_type i databasen.
//Se V95__aksjonstype_oppdater_journalposttype.sql for eksempel
public enum AksjonsTypeCode {
	ARKIVERING,
	AVBRYT,
	EKSPEDER,
	ENDRE_METADATA,
	ENDRE_SKJERMING,
	ENDRE_JOURNALPOSTTYPE,
	FEILREGISTRER_SAKSTILKNYTNING,
	FERDIGSTILL,
	KASSERING,
	KOPIER_JOURNALPOST,
	OPPHEV_FEILREGISTRERING,
	OVERSTYR_INNSYN,
	OPPRETT,
	SAKSTILKNYTNING,
	SLETTING,
	TILBAKE_TIL_MOTTATT,
	UKJENT_BRUKER,
	UTGAAR,
	TILKNYTT_NYTT_DOKUMENT,
	SPLITT,
	KOPIER_DOKUMENT,
	ENDRE_DOKUMENT,
	OPPRETT_FRA_SPLITT
}
