type Journalpost {
    journalpostId: ID!
    journalForendeEnhetId: String
    journalposttype: String
    tema: String
    kanalReferanseId: String
    innhold: String
    journalDato: String
    journalstatus: String
    land: String
    mottakskanal: String
    utsendingskanal: String
    avsenderMottaker: String
    avsenderMottakerId: String
    journalfortAvNavn: String
    opprettetAvNavn: String
    endretAvNavn: String
    opprettetKildeNavn: String
    endretKildeNavn: String
    saksrelasjon: Saksrelasjon
    behandlingsrelasjon: Behandlingsrelasjon
    brukere: [Bruker]
    kryssreferanser: [Kryssreferanse]
    tilleggsopplysninger: [GraphQlMap]
    returInfos: [ReturInfo]
    journalpostDokumentInfoRelasjoner: [JournalpostDokumentInfoRelasjon]
}

type DokumentInfo {
    dokumentInfoId: ID!
    #Dette er tittel på dokumentet
    tittel: String
    #Navnet på bruker som gjorde endring sist på dokumentet
    dokumenttypeId: String
    brevkode: String
    brevgruppe: String
    kategori: String
    dokumentstatus: String
    dokumentFerdigDato: String
    opprettetKildeNavn: String
    endretKildeNavn: String
    endretAvNavn: String
    originalJournalpost: Journalpost
    tilleggsopplysninger: [GraphQlMap]
    journalpostRelasjoner: [JournalpostDokumentInfoRelasjon]
    fildetaljerListe: [FilDetaljer]
    skannetInnholdListe: [SkannetInnhold]
}

type Bruker {
    brukerInfoId: ID!
    brukerType: String
    brukerId: String
}

type Saksrelasjon {
    feilregistrert: Boolean
    fagsystem: String
    endretAvNavn: String
}

type Kryssreferanse {
    kryssreferanseId: Long
    referanseId: String
    referanseNr: Long
    referanseType: String
}

type Behandlingsrelasjon {
    behandlingsrelasjonId: Long
    behandlingsId: String
    behandlingsType: String
}

type SkannetInnhold {
    skannetInnholdId: Long
    vedleggNr: Int
    vedleggInnhold: String
    dokumenttypeid: String
}

type ReturInfo {
    returInfoId: Long
    returDato: String
    adresseSendtIgjen: String
    sendtIgjenDato: String
    arsakRetur: String
}

type JournalpostDokumentInfoRelasjon {
    journalpostDokumentInfoRelasjonId: ID!
    tilknyttetAvNavn: String
    tilknyttetJournalpostSom: String
    dokumentInfo: DokumentInfo
    journalpost: Journalpost
}

type FilDetaljer {
    fildetaljerId: ID!
    filtype: String
    filUuid: String
    onDemandId: String
    filnavn: String
    batchNavn: String
    filstorrelse: String
    variantFormat: String
}

type GraphQlMap {
    key: String
    value: String
}

