CREATE TABLE T_BJOARK015_ARBTB
(
  JOURNALFORENDE_ENHET    VARCHAR2(20),
  FILNAVN                 VARCHAR2(50),
  ANTALL_SIDER            NUMBER(11),
  VERSJON                 NUMBER(11)   NOT NULL,
  DATO_OPPRETTET          TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV            VARCHAR2(20) NOT NULL,
  DATO_ENDRET             TIMESTAMP(6),
  ENDRET_AV               VARCHAR2(20),
  BJOARK015_ARBTB_ID      NUMBER(11)   NOT NULL
    CONSTRAINT XPKBJOARK015_ARBTB
    PRIMARY KEY USING INDEX,
  FIL                     BLOB,
  BIDRAG_MELLOMLAGRING_ID NUMBER(8)    NOT NULL
    CONSTRAINT R_67
    REFERENCES T_BIDRAG_MELLOMLAGRING
);

CREATE UNIQUE INDEX XIF1BJOARK015_ARBTB
  ON T_BJOARK015_ARBTB (BIDRAG_MELLOMLAGRING_ID ASC);

CREATE TABLE T_BJOARK005_ARBTB
(
  FIL_ID_FK          VARCHAR2(200),
  STATUS             VARCHAR2(20),
  RECORD             VARCHAR2(1000),
  FEILMELDING        VARCHAR2(500),
  VERSJON            NUMBER(11)   NOT NULL,
  DATO_OPPRETTET     TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV       VARCHAR2(20) NOT NULL,
  DATO_ENDRET        TIMESTAMP(6),
  ENDRET_AV          VARCHAR2(20),
  BJOARK005_ARBTB_ID NUMBER(11)   NOT NULL
    CONSTRAINT XPKBJOARK005_ARBTB
    PRIMARY KEY
);

CREATE TABLE T_BJOARK010_ARBTB
(
  BJOARK010_ARBTB_ID NUMBER(11)    NOT NULL
    CONSTRAINT XPKT_BJOARK010_ARBTB
    PRIMARY KEY,
  ON_DEMAND_ID       VARCHAR2(50)  NOT NULL,
  SAK_NR             VARCHAR2(20),
  BRUKER_ID          VARCHAR2(11)  NOT NULL,
  BRUKER_TYPE        VARCHAR2(20)  NOT NULL,
  JOURNALPOST_TYPE   VARCHAR2(20)  NOT NULL,
  FAGOMRADE          VARCHAR2(20)  NOT NULL,
  DATO_JOURNAL       TIMESTAMP(6)  NOT NULL,
  JOURNAL_STATUS     VARCHAR2(20)  NOT NULL,
  INNHOLD            VARCHAR2(500) NOT NULL,
  MOTTAKER_NAVN      VARCHAR2(200),
  MOTTAKER_ID        VARCHAR2(20),
  JOURNALF_ENHET     VARCHAR2(20)  NOT NULL,
  DATO_SENDT_PRINT   TIMESTAMP(6),
  OPPRETTET_AV_NAVN  VARCHAR2(50)  NOT NULL,
  DOKUMENT_KATEGORI  VARCHAR2(20)  NOT NULL,
  DATO_DOK_FERDIG    TIMESTAMP(6)  NOT NULL,
  BREVKODE           VARCHAR2(50)  NOT NULL,
  SENSITIVT          CHAR          NOT NULL,
  INNSKR_PARTSINNSYN CHAR,
  FIL_ID_FK          VARCHAR2(200) NOT NULL,
  STATUS             VARCHAR2(20)  NOT NULL,
  FEILMELDING        VARCHAR2(500),
  VERSJON            NUMBER(11)    NOT NULL,
  DATO_OPPRETTET     TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV       VARCHAR2(20)  NOT NULL,
  DATO_ENDRET        TIMESTAMP(6),
  ENDRET_AV          VARCHAR2(20),
  DOKUMENT           BLOB,
  GSAK_SAK_NR        VARCHAR2(20)
);

CREATE TABLE T_BATCH_STEP_EXECUTION
(
  STEP_EXECUTION_ID  NUMBER(19)    NOT NULL
    CONSTRAINT XPKBATCH_STEP_EXECUTION
    PRIMARY KEY,
  VERSION            NUMBER(19)    NOT NULL,
  STEP_NAME          VARCHAR2(100) NOT NULL,
  JOB_EXECUTION_ID   NUMBER(19)    NOT NULL,
  START_TIME         TIMESTAMP(6)  NOT NULL,
  END_TIME           TIMESTAMP(6),
  STATUS             VARCHAR2(10),
  COMMIT_COUNT       NUMBER(19),
  READ_COUNT         NUMBER(19),
  FILTER_COUNT       NUMBER(19),
  WRITE_COUNT        NUMBER(19),
  READ_SKIP_COUNT    NUMBER(19),
  WRITE_SKIP_COUNT   NUMBER(19),
  PROCESS_SKIP_COUNT NUMBER(19),
  ROLLBACK_COUNT     NUMBER(19),
  EXIT_CODE          VARCHAR2(100),
  EXIT_MESSAGE       VARCHAR2(2500 CHAR),
  LAST_UPDATED       TIMESTAMP(6)
);

CREATE TABLE T_BATCH_JOB_PARAMS
(
  JOB_INSTANCE_ID NUMBER(19)    NOT NULL,
  TYPE_CD         VARCHAR2(6)   NOT NULL,
  KEY_NAME        VARCHAR2(100) NOT NULL,
  STRING_VAL      VARCHAR2(250),
  DATE_VAL        TIMESTAMP(6),
  LONG_VAL        NUMBER(19),
  DOUBLE_VAL      NUMBER
);

CREATE TABLE T_BATCH_JOB_INSTANCE
(
  JOB_INSTANCE_ID NUMBER(19)    NOT NULL
    CONSTRAINT XPKBATCH_JOB_INSTANCE
    PRIMARY KEY,
  VERSION         NUMBER(19),
  JOB_NAME        VARCHAR2(100) NOT NULL,
  JOB_KEY         VARCHAR2(32)  NOT NULL,
  CONSTRAINT JOB_INST_UN
  UNIQUE (JOB_NAME, JOB_KEY)
);

ALTER TABLE T_BATCH_JOB_PARAMS
  ADD CONSTRAINT JOB_INST_PARAMS_FK
FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES T_BATCH_JOB_INSTANCE;

CREATE TABLE T_BATCH_JOB_EXECUTION
(
  JOB_EXECUTION_ID NUMBER(19)   NOT NULL
    CONSTRAINT XPKBATCH_JOB_EXECUTION
    PRIMARY KEY,
  VERSION          NUMBER(19),
  JOB_INSTANCE_ID  NUMBER(19)   NOT NULL
    CONSTRAINT JOB_INST_EXEC_FK
    REFERENCES T_BATCH_JOB_INSTANCE,
CREATE_TIME      TIMESTAMP(6) NOT NULL,
  START_TIME       TIMESTAMP(6),
  END_TIME         TIMESTAMP(6),
  STATUS           VARCHAR2(10),
  EXIT_CODE        VARCHAR2(100),
  EXIT_MESSAGE     VARCHAR2(2500),
  LAST_UPDATED     TIMESTAMP(6)
);

ALTER TABLE T_BATCH_STEP_EXECUTION
  ADD CONSTRAINT JOB_EXEC_STEP_FK
FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES T_BATCH_JOB_EXECUTION;

CREATE TABLE T_BATCH
(
  BATCH_ID       NUMBER(11)    NOT NULL
    CONSTRAINT IBATCHU
    PRIMARY KEY,
  BATCH_NAME     VARCHAR2(100) NOT NULL,
  SLICE          NUMBER(11)    NOT NULL,
  STATUS         VARCHAR2(100) NOT NULL,
  SLICE_START    VARCHAR2(255),
  SLICE_END      VARCHAR2(255),
  PARAMETERS     VARCHAR2(500) NOT NULL,
  DATO_OPPRETTET TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV   VARCHAR2(20)  NOT NULL,
  DATO_ENDRET    TIMESTAMP(6)  NOT NULL,
  ENDRET_AV      VARCHAR2(20)  NOT NULL,
  VERSJON        NUMBER(11)    NOT NULL,
  CONSTRAINT INAMESLICEU
  UNIQUE (SLICE, BATCH_NAME)
);

CREATE SEQUENCE T_BATCH_ID_SEQ NOCACHE;

CREATE TABLE T_BATCH_JOB_EXECUTION_CONTEXT
(
  JOB_EXECUTION_ID   NUMBER(19)          NOT NULL
    CONSTRAINT XPKBATCH_JOB_EXECUTION_CONTEXT
    PRIMARY KEY
    CONSTRAINT JOB_EXEC_CTX_FK
    REFERENCES T_BATCH_JOB_EXECUTION,
  SHORT_CONTEXT      VARCHAR2(2500 CHAR) NOT NULL,
  SERIALIZED_CONTEXT CLOB
);

CREATE TABLE T_BATCH_STEP_EXECUTION_CONTEXT
(
  STEP_EXECUTION_ID  NUMBER(19)     NOT NULL
    CONSTRAINT XPKBATCH_STEP_EXECUTION_CONTEX
    PRIMARY KEY
    CONSTRAINT STEP_EXEC_CTX_FK
    REFERENCES T_BATCH_STEP_EXECUTION,
  SHORT_CONTEXT      VARCHAR2(2500) NOT NULL,
  SERIALIZED_CONTEXT CLOB
);

CREATE SEQUENCE T_BATCH_JOB_EXECUTION_SEQ;

CREATE SEQUENCE T_BATCH_STEP_EXECUTION_SEQ;

CREATE SEQUENCE T_BATCH_JOB_SEQ;

CREATE SEQUENCE T_BJOARK005_ARBTB_SEQ
CACHE 30;

CREATE SEQUENCE T_BJOARK010_ARBTB_SEQ
CACHE 30;

CREATE SEQUENCE T_BJOARK015_ARBTB_SEQ
CACHE 30;

CREATE TABLE T_BJOARK015_LOPENR
(
  LOPENR NUMBER(4) NOT NULL
);

CREATE UNIQUE INDEX XAK1T_BJOARK015_LOPENR
  ON T_BJOARK015_LOPENR ('1');

CREATE TRIGGER T_BATCH_ID_TRIGGER
  BEFORE INSERT
  ON T_BATCH
  FOR EACH ROW
BEGIN
  SELECT T_BATCH_ID_SEQ.NEXTVAL
  INTO :NEW.BATCH_ID
  FROM DUAL;
END;
/