CREATE TABLE T_K_BRUKER_T
  (
    K_BRUKER_T     VARCHAR2(20)  NOT NULL
      CONSTRAINT XPKK_BRUKER_T
      PRIMARY KEY,
    DEKODE         VARCHAR2(200) NOT NULL,
    DATO_FOM       DATE          NOT NULL,
    DATO_TOM       DATE,
    ER_GYLDIG      CHAR          NOT NULL,
    DATO_OPPRETTET TIMESTAMP(6)  NOT NULL,
    OPPRETTET_AV   VARCHAR2(20)  NOT NULL,
    DATO_ENDRET    TIMESTAMP(6)  NOT NULL,
    ENDRET_AV      VARCHAR2(20)  NOT NULL
);

  CREATE TABLE T_K_VARIANT_FORMAT
(
  K_VARIANT_FORMAT VARCHAR2(20)  NOT NULL
    CONSTRAINT XPKK_VARIANT_FORMAT
    PRIMARY KEY,
  DEKODE           VARCHAR2(200) NOT NULL,
  DATO_FOM         DATE          NOT NULL,
  DATO_TOM         DATE,
  ER_GYLDIG        CHAR          NOT NULL,
  DATO_OPPRETTET   TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV     VARCHAR2(20)  NOT NULL,
  DATO_ENDRET      TIMESTAMP(6)  NOT NULL,
  ENDRET_AV        VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_UTSENDINGS_KANAL
(
  K_UTSENDINGS_KANAL VARCHAR2(20)  NOT NULL
    CONSTRAINT IKUTSENDKANALU
    PRIMARY KEY,
  DEKODE             VARCHAR2(200) NOT NULL,
  DATO_FOM           DATE          NOT NULL,
  DATO_TOM           DATE,
  ER_GYLDIG          CHAR          NOT NULL,
  DATO_OPPRETTET     TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV       VARCHAR2(20)  NOT NULL,
  DATO_ENDRET        TIMESTAMP(6)  NOT NULL,
  ENDRET_AV          VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_ARSAK_RETUR
(
  K_ARSAK_RETUR  VARCHAR2(20)  NOT NULL
    CONSTRAINT XPKK_ARSAK_RETUR
    PRIMARY KEY,
  DEKODE         VARCHAR2(200) NOT NULL,
  DATO_FOM       DATE          NOT NULL,
  DATO_TOM       DATE,
  ER_GYLDIG      CHAR          NOT NULL,
  DATO_OPPRETTET TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV   VARCHAR2(20)  NOT NULL,
  DATO_ENDRET    TIMESTAMP(6)  NOT NULL,
  ENDRET_AV      VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_ONDEMAND_INST
(
  K_ONDEMAND_INST VARCHAR2(20)  NOT NULL
    CONSTRAINT XPKK_ONDEMAND_INST
    PRIMARY KEY,
  DEKODE          VARCHAR2(200) NOT NULL,
  DATO_FOM        DATE          NOT NULL,
  DATO_TOM        DATE,
  ER_GYLDIG       CHAR          NOT NULL,
  DATO_OPPRETTET  TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV    VARCHAR2(20)  NOT NULL,
  DATO_ENDRET     TIMESTAMP(6)  NOT NULL,
  ENDRET_AV       VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_KATEGORI_T
(
  K_KATEGORI_T   VARCHAR2(20)  NOT NULL
    CONSTRAINT IKKATEGORIU
    PRIMARY KEY,
  DEKODE         VARCHAR2(200) NOT NULL,
  DATO_FOM       DATE          NOT NULL,
  DATO_TOM       DATE,
  ER_GYLDIG      CHAR          NOT NULL,
  DATO_OPPRETTET TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV   VARCHAR2(20)  NOT NULL,
  DATO_ENDRET    TIMESTAMP(6)  NOT NULL,
  ENDRET_AV      VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_JOURNAL_S
(
  K_JOURNAL_S    VARCHAR2(20)  NOT NULL
    CONSTRAINT IKJOURNALU
    PRIMARY KEY,
  DEKODE         VARCHAR2(200) NOT NULL,
  DATO_FOM       DATE          NOT NULL,
  DATO_TOM       DATE,
  ER_GYLDIG      CHAR          NOT NULL,
  DATO_OPPRETTET TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV   VARCHAR2(20)  NOT NULL,
  DATO_ENDRET    TIMESTAMP(6)  NOT NULL,
  ENDRET_AV      VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_FIL_T
(
  K_FIL_T        VARCHAR2(20)  NOT NULL
    CONSTRAINT XPKK_FIL_T
    PRIMARY KEY,
  DEKODE         VARCHAR2(200) NOT NULL,
  DATO_FOM       DATE          NOT NULL,
  DATO_TOM       DATE,
  ER_GYLDIG      CHAR          NOT NULL,
  DATO_OPPRETTET TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV   VARCHAR2(20)  NOT NULL,
  DATO_ENDRET    TIMESTAMP(6)  NOT NULL,
  ENDRET_AV      VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_FAKT_DIS_KANAL
(
  K_FAKT_DIS_KANAL VARCHAR2(20)  NOT NULL
    CONSTRAINT IKFAKTDISKANALU
    PRIMARY KEY,
  DEKODE           VARCHAR2(200) NOT NULL,
  DATO_FOM         DATE          NOT NULL,
  DATO_TOM         DATE,
  ER_GYLDIG        CHAR          NOT NULL,
  DATO_OPPRETTET   TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV     VARCHAR2(20)  NOT NULL,
  DATO_ENDRET      TIMESTAMP(6)  NOT NULL,
  ENDRET_AV        VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_DOKUMENT_S
(
  K_DOKUMENT_S   VARCHAR2(20)  NOT NULL
    CONSTRAINT XPKK_DOKUMENT_S
    PRIMARY KEY,
  DEKODE         VARCHAR2(200) NOT NULL,
  DATO_FOM       DATE          NOT NULL,
  DATO_TOM       DATE,
  ER_GYLDIG      CHAR          NOT NULL,
  DATO_OPPRETTET TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV   VARCHAR2(20)  NOT NULL,
  DATO_ENDRET    TIMESTAMP(6)  NOT NULL,
  ENDRET_AV      VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_JOURNALPOST_T
(
  K_JOURNALPOST_T VARCHAR2(20)  NOT NULL
    CONSTRAINT IKJOURNALPTU
    PRIMARY KEY,
  DEKODE          VARCHAR2(200) NOT NULL,
  DATO_FOM        DATE          NOT NULL,
  DATO_TOM        DATE,
  ER_GYLDIG       CHAR          NOT NULL,
  DATO_OPPRETTET  TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV    VARCHAR2(20)  NOT NULL,
  DATO_ENDRET     TIMESTAMP(6)  NOT NULL,
  ENDRET_AV       VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_FAGSYSTEM
(
  K_FAGSYSTEM    VARCHAR2(20)  NOT NULL
    CONSTRAINT XPKK_FAGSYSTEM
    PRIMARY KEY,
  DEKODE         VARCHAR2(200) NOT NULL,
  DATO_FOM       DATE          NOT NULL,
  DATO_TOM       DATE,
  ER_GYLDIG      CHAR          NOT NULL,
  DATO_OPPRETTET TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV   VARCHAR2(20)  NOT NULL,
  DATO_ENDRET    TIMESTAMP(6)  NOT NULL,
  ENDRET_AV      VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_FAGOMRADE
(
  K_FAGOMRADE    VARCHAR2(20)  NOT NULL
    CONSTRAINT IKFAGSYSTEMU
    PRIMARY KEY,
  DEKODE         VARCHAR2(200) NOT NULL,
  DATO_FOM       DATE          NOT NULL,
  DATO_TOM       DATE,
  ER_GYLDIG      CHAR          NOT NULL,
  DATO_OPPRETTET TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV   VARCHAR2(20)  NOT NULL,
  DATO_ENDRET    TIMESTAMP(6)  NOT NULL,
  ENDRET_AV      VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_MOTTAKS_KANAL
(
  K_MOTTAKS_KANAL VARCHAR2(20)  NOT NULL
    CONSTRAINT IKMOTTAKSKANALU
    PRIMARY KEY,
  DEKODE          VARCHAR2(200) NOT NULL,
  DATO_FOM        DATE          NOT NULL,
  DATO_TOM        DATE,
  ER_GYLDIG       CHAR          NOT NULL,
  DATO_OPPRETTET  TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV    VARCHAR2(20)  NOT NULL,
  DATO_ENDRET     TIMESTAMP(6)  NOT NULL,
  ENDRET_AV       VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_TILKN_JP_SOM
(
  K_TILKN_JP_SOM VARCHAR2(20)  NOT NULL
    CONSTRAINT XPKK_TILKN_JP_SOM
    PRIMARY KEY,
  DEKODE         VARCHAR2(200) NOT NULL,
  DATO_FOM       DATE          NOT NULL,
  DATO_TOM       DATE,
  ER_GYLDIG      CHAR          NOT NULL,
  DATO_OPPRETTET TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV   VARCHAR2(20)  NOT NULL,
  DATO_ENDRET    TIMESTAMP(6)  NOT NULL,
  ENDRET_AV      VARCHAR2(20)  NOT NULL
);

CREATE TABLE T_K_REFERANSE_T
(
  K_REFERANSE_T  VARCHAR2(20)  NOT NULL
    CONSTRAINT XPKK_REFERANSE_T
    PRIMARY KEY,
  DEKODE         VARCHAR2(200) NOT NULL,
  DATO_FOM       DATE          NOT NULL,
  DATO_TOM       DATE,
  ER_GYLDIG      CHAR          NOT NULL,
  DATO_OPPRETTET TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV   VARCHAR2(20)  NOT NULL,
  DATO_ENDRET    TIMESTAMP(6)  NOT NULL,
  ENDRET_AV      VARCHAR2(20)  NOT NULL
);