CREATE TABLE T_JOURNALPOST
(
  JOURNALPOST_ID       NUMBER(11)   NOT NULL
    CONSTRAINT IJOURNALPU
    PRIMARY KEY,
  JOURNALF_ENHET       VARCHAR2(20),
  OPPRETTET_AV_NAVN    VARCHAR2(50),
  DATO_JOURNAL         TIMESTAMP(6),
  ANTALL_RETUR         NUMBER(11),
  DATO_AVS_RETUR       TIMESTAMP(6),
  INNHOLD              VARCHAR2(500),
  KRAV_TYPE            VARCHAR2(20),
  MERKNAD              VARCHAR2(2000),
  FORDELING            VARCHAR2(200),
  ORIGINAL_BESTILT     CHAR,
  ENDRET_AV_NAVN       VARCHAR2(50),
  OPPRETTET_AV         VARCHAR2(20) NOT NULL,
  DATO_ENDRET          TIMESTAMP(6),
  ENDRET_AV            VARCHAR2(20),
  DATO_SENDT_PRINT     TIMESTAMP(6),
  VERSJON              NUMBER(11)   NOT NULL,
  K_FAGOMRADE          VARCHAR2(20),
  K_JOURNAL_S          VARCHAR2(20) NOT NULL,
  DATO_OPPRETTET       TIMESTAMP(6) NOT NULL,
  DATO_DOKUMENT        TIMESTAMP(6),
  AVSEND_MOTTAKER      VARCHAR2(200),
  AVSEND_MOTTAK_ID     VARCHAR2(50),
  JOURNALFORT_AV_NAVN  VARCHAR2(50),
  DATO_MOTTATT         TIMESTAMP(6),
  LAND                 VARCHAR2(50),
  K_FAKT_DIS_KANAL     VARCHAR2(20),
  ELEKTRONISK_DISTR    CHAR,
  DATO_EKSPEDERT       TIMESTAMP(6),
  DATO_LEST            TIMESTAMP(6),
  MOTTATT_ADRESSAT     TIMESTAMP(6),
  OPPRETTET_KILDE_NAVN VARCHAR2(20) NOT NULL,
  K_JOURNALPOST_T      VARCHAR2(20) NOT NULL,
  K_UTSENDINGS_KANAL   VARCHAR2(20),
  K_MOTTAKS_KANAL      VARCHAR2(20),
  ENDRET_KILDE_NAVN    VARCHAR2(20),
  SIGNATUR             CHAR
);

 CREATE INDEX XIE1JOURNALP
  ON T_JOURNALPOST (DATO_SENDT_PRINT);

  CREATE INDEX XIF1JOURNALP
  ON T_JOURNALPOST (K_FAGOMRADE);

  CREATE INDEX XIF2JOURNALP
  ON T_JOURNALPOST (K_JOURNAL_S);

  CREATE INDEX XIE2JOURNALP
  ON T_JOURNALPOST (AVSEND_MOTTAK_ID) ;

CREATE INDEX XIE3JOURNALP
  ON T_JOURNALPOST (DATO_MOTTATT) ;

CREATE INDEX XIF3JOURNALP
  ON T_JOURNALPOST (K_FAKT_DIS_KANAL) ;

CREATE INDEX XIE4JOURNALPOST
  ON T_JOURNALPOST (K_JOURNALPOST_T, K_JOURNAL_S, DATO_SENDT_PRINT) ;

CREATE INDEX XIF4JOURNALP
  ON T_JOURNALPOST (K_JOURNALPOST_T) ;

CREATE INDEX XIF6JOURNALP
  ON T_JOURNALPOST (K_UTSENDINGS_KANAL) ;

CREATE INDEX XIF5JOURNALP
  ON T_JOURNALPOST (K_MOTTAKS_KANAL) ;

  ALTER  TABLE T_JOURNALPOST
  ADD CONSTRAINT T_JOURNALPOST_R_55
FOREIGN KEY (K_UTSENDINGS_KANAL) REFERENCES T_K_UTSENDINGS_KANAL ;

ALTER TABLE T_JOURNALPOST
  ADD CONSTRAINT T_JOURNALPOST_R_10
FOREIGN KEY (K_JOURNAL_S) REFERENCES T_K_JOURNAL_S ;

ALTER TABLE T_JOURNALPOST
  ADD CONSTRAINT T_JOURNALPOST_R_50
FOREIGN KEY (K_FAKT_DIS_KANAL) REFERENCES T_K_FAKT_DIS_KANAL ;

ALTER TABLE T_JOURNALPOST
  ADD CONSTRAINT T_JOURNALPOST_R_51
FOREIGN KEY (K_JOURNALPOST_T) REFERENCES T_K_JOURNALPOST_T ;

ALTER TABLE T_JOURNALPOST
  ADD CONSTRAINT T_JOURNALPOST_R_9
FOREIGN KEY (K_FAGOMRADE) REFERENCES T_K_FAGOMRADE ;

ALTER TABLE T_JOURNALPOST
  ADD CONSTRAINT T_JOURNALPOST_R_54
FOREIGN KEY (K_MOTTAKS_KANAL) REFERENCES T_K_MOTTAKS_KANAL ;

CREATE TABLE T_DOKUMENT_INFO
(
  DOKUMENT_INFO_ID              NUMBER(11)   NOT NULL
    CONSTRAINT IDOKUMENTINFOU
    PRIMARY KEY,
  BREV_KODE                     VARCHAR2(50),
  BREV_GRUPPE                   VARCHAR2(50),
  KONVERTERT_SYSTEM             VARCHAR2(20),
  SENSITIVT                     CHAR,
  DATO_OPPRETTET                TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV                  VARCHAR2(20) NOT NULL,
  DATO_ENDRET                   TIMESTAMP(6),
  ENDRET_AV                     VARCHAR2(20),
  VERSJON                       NUMBER(11)   NOT NULL,
  ENDRET_AV_NAVN                VARCHAR2(50),
  K_KATEGORI_T                  VARCHAR2(20),
  OPPRETTET_KILDE_NAVN          VARCHAR2(20) NOT NULL,
  K_DOKUMENT_S                  VARCHAR2(20),
  DATO_DOK_FERDIG               TIMESTAMP(6),
  TITTEL                        VARCHAR2(500),
  KONFIDENSIALITET              VARCHAR2(20),
  INTEGRITET                    VARCHAR2(20),
  TILGJENGELIGHET               VARCHAR2(20),
  INNSKR_PARTSINNSYN            CHAR,
  ORGAN_INTERNT                 CHAR,
  ORIG_JOURNALPOST_ID           NUMBER(11)
    CONSTRAINT T_DOKUMENT_INFO_R_53
    REFERENCES T_JOURNALPOST,
  ENDRET_KILDE_NAVN             VARCHAR2(20),
  DOKUMENTTYPE_ID               VARCHAR2(20)
) ;

CREATE INDEX XIF3DOKUMENTINFO
  ON T_DOKUMENT_INFO (K_KATEGORI_T) ;

CREATE INDEX XIF4DOKUMENTINFO
  ON T_DOKUMENT_INFO (K_DOKUMENT_S) ;

CREATE INDEX XIF5DOKUMENTINFO
  ON T_DOKUMENT_INFO (ORIG_JOURNALPOST_ID) ;

ALTER TABLE T_DOKUMENT_INFO
  ADD CONSTRAINT T_DOKUMENT_INFO_R_4
FOREIGN KEY (K_KATEGORI_T) REFERENCES T_K_KATEGORI_T ;

ALTER TABLE T_DOKUMENT_INFO
  ADD CONSTRAINT T_DOKUMENT_INFO_R_52
FOREIGN KEY (K_DOKUMENT_S) REFERENCES T_K_DOKUMENT_S ;

CREATE TABLE T_BRUKER (
  BRUKERINFO_ID        NUMBER(11)   NOT NULL
    CONSTRAINT IBRUKERU
    PRIMARY KEY,
  BRUKER_ID            CHAR(11)     NOT NULL,
  DATO_OPPRETTET       TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV         VARCHAR2(20) NOT NULL,
  DATO_ENDRET          TIMESTAMP(6),
  ENDRET_AV            VARCHAR2(20),
  VERSJON              NUMBER(11)   NOT NULL,
  JOURNALPOST_ID       NUMBER(11)   NOT NULL
    CONSTRAINT T_BRUKER_R_6
    REFERENCES T_JOURNALPOST,
  K_BRUKER_T           VARCHAR2(20) NOT NULL,
  OPPRETTET_KILDE_NAVN VARCHAR2(20) NOT NULL,
  ENDRET_KILDE_NAVN    VARCHAR2(20)
) ;

CREATE INDEX XIE1T_BRUKER
  ON T_BRUKER (BRUKER_ID) ;

CREATE INDEX XIF1BRUKER
  ON T_BRUKER (JOURNALPOST_ID) ;

CREATE INDEX XIF2BRUKER
  ON T_BRUKER (K_BRUKER_T) ;

ALTER TABLE T_BRUKER
  ADD CONSTRAINT T_BRUKER_R_8
FOREIGN KEY (K_BRUKER_T) REFERENCES T_K_BRUKER_T ;

CREATE TABLE T_PARTISJON_VERIFISERING
(
  MAALING           CHAR(128),
  TID               DATE,
  TYPE              VARCHAR2(128),
  OBJEKT            VARCHAR2(128),
  TABELL            VARCHAR2(128),
  ANTALL_RADER      NUMBER,
  STATUS            VARCHAR2(128),
  R_CONSTRAINT_NAME VARCHAR2(128),
  INDEX_NAME        VARCHAR2(128),
  SEARCH_CONDITION  VARCHAR2(4000),
  UNIQUENESS        VARCHAR2(50)
) ;

CREATE TABLE T_RIKSARKIV_FILUUID (
  FIL_UUID VARCHAR2(36)
    CONSTRAINT FIL_UUID_PK
    PRIMARY KEY,
  K_FIL_T  VARCHAR2(20)) ;

CREATE TABLE T_RIKSARKIV_SAKSREF
(
  SAK_NR   VARCHAR2(20) NOT NULL
    CONSTRAINT SAK_NR_PK
    PRIMARY KEY,
  SAK_TYPE VARCHAR2(20) NOT NULL
) ;

CREATE TABLE T_BIDRAG_MELLOMLAGRING
(
  BIDRAG_MELLOMLAGRING_ID NUMBER(8)    NOT NULL
    CONSTRAINT XPKT_BIDRAG_MELLOMLAGRING
    PRIMARY KEY,
  AVSENDER_FNR            VARCHAR2(11) NOT NULL,
  DATO_MOTTATT            TIMESTAMP(6) NOT NULL,
  STATUS                  VARCHAR2(20) NOT NULL,
  DATO_OPPRETTET          TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV            VARCHAR2(20) NOT NULL,
  DATO_ENDRET             TIMESTAMP(6),
  ENDRET_AV               VARCHAR2(20),
  VERSJON                 NUMBER(11)   NOT NULL
) ;

--------------------------------------------------------
--  DDL for Table T_BEHANDLINGSRELASJON
--------------------------------------------------------
CREATE TABLE T_BEHANDLINGSRELASJON
(
  BEHANDLINGSRELASJON_ID NUMBER(11)   NOT NULL
    CONSTRAINT XPKT_BEHANDLING_RELASJON
    PRIMARY KEY,
  BEHANDLING_ID          VARCHAR2(20) NOT NULL,
  BEHANDLING_TYPE        VARCHAR2(20) NOT NULL,
  DATO_OPPRETTET         TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV           VARCHAR2(20) NOT NULL,
  DATO_ENDRET            TIMESTAMP(6),
  ENDRET_AV              VARCHAR2(20),
  VERSJON                NUMBER(11)   NOT NULL,
  OPPRETTET_KILDE_NAVN   VARCHAR2(20) NOT NULL,
  ENDRET_KILDE_NAVN      VARCHAR2(20),
  JOURNALPOST_ID         NUMBER(11)   NOT NULL
    CONSTRAINT R_63
    REFERENCES T_JOURNALPOST
) ;

CREATE UNIQUE INDEX XIF1T_BEHANDLING_RELASJON
  ON T_BEHANDLINGSRELASJON (JOURNALPOST_ID) ;

CREATE TABLE T_DOK_INFO_TILLEGG
(
  NOKKEL           VARCHAR2(20) NOT NULL,
  VERDI            VARCHAR2(50) NOT NULL,
  DOKUMENT_INFO_ID NUMBER(11)   NOT NULL
    CONSTRAINT R_62
    REFERENCES T_DOKUMENT_INFO,
  CONSTRAINT XPKT_DOK_INFO_TILLEGG
  PRIMARY KEY (DOKUMENT_INFO_ID, NOKKEL)
) ;

CREATE INDEX XIF1T_DOK_INFO_TILLEGG
  ON T_DOK_INFO_TILLEGG (DOKUMENT_INFO_ID) ;

CREATE TABLE T_DOKUMENT_MAL_INFO
(
  BREV_KODE       VARCHAR2(50)  NOT NULL
    CONSTRAINT XPKDOK_MAL_METADATA
    PRIMARY KEY,
  BREV_GRUPPE     VARCHAR2(50)  NOT NULL,
  TITTEL          VARCHAR2(500) NOT NULL,
  REDIGERBART     CHAR          NOT NULL,
  K_KATEGORI_T    VARCHAR2(20)  NOT NULL,
  K_JOURNALPOST_T VARCHAR2(20)  NOT NULL,
  ORGAN_INTERNT   CHAR,
  SENSITIVT       CHAR,
  DATO_OPPRETTET  TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV    VARCHAR2(20)  NOT NULL,
  DATO_ENDRET     TIMESTAMP(6)  NOT NULL,
  ENDRET_AV       VARCHAR2(20)  NOT NULL
) ;

CREATE INDEX XIF1DOK_MAL_METADATA
  ON T_DOKUMENT_MAL_INFO (K_KATEGORI_T) ;

CREATE INDEX XIF2DOK_MAL_METADATA
  ON T_DOKUMENT_MAL_INFO (K_JOURNALPOST_T) ;

ALTER TABLE T_DOKUMENT_MAL_INFO
  ADD CONSTRAINT T_DOKUMENT_MAL_INFO_R_58
FOREIGN KEY (K_KATEGORI_T) REFERENCES T_K_KATEGORI_T ;

ALTER TABLE T_DOKUMENT_MAL_INFO
  ADD CONSTRAINT T_DOKUMENT_MAL_INFO_R_59
FOREIGN KEY (K_JOURNALPOST_T) REFERENCES T_K_JOURNALPOST_T ;

CREATE TABLE T_RETUR_INFO
(
  RETUR_INFO_ID        NUMBER(11)   NOT NULL
    CONSTRAINT XPKRETUR_INFO
    PRIMARY KEY,
  DATO_RETUR           TIMESTAMP(6) NOT NULL,
  ADR_SENDT_IGJEN      VARCHAR2(200),
  DATO_SENDT_IGJEN     TIMESTAMP(6),
  DATO_OPPRETTET       TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV         VARCHAR2(20),
  DATO_ENDRET          TIMESTAMP(6),
  ENDRET_AV            VARCHAR2(20),
  VERSJON              NUMBER(11)   NOT NULL,
  OPPRETTET_KILDE_NAVN VARCHAR2(20) NOT NULL,
  K_ARSAK_RETUR        VARCHAR2(20) NOT NULL,
  JOURNALPOST_ID       NUMBER(11)   NOT NULL,
  ENDRET_KILDE_NAVN    VARCHAR2(20)
) ;

CREATE INDEX XIF1RETUR_INFO
  ON T_RETUR_INFO (K_ARSAK_RETUR) ;

CREATE INDEX XIF2RETUR_INFO
  ON T_RETUR_INFO (JOURNALPOST_ID) ;

CREATE TABLE T_KRYSSREFERANSE
(
  KRYSSREFERANSE_ID    NUMBER(11)   NOT NULL
    CONSTRAINT XPKKRYSSREFERANSE
    PRIMARY KEY,
  REFERANSE_ID         VARCHAR2(20) NOT NULL,
  REFERANSE_NR         NUMBER(11),
  DATO_OPPRETTET       TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV         VARCHAR2(20) NOT NULL,
  DATO_ENDRET          TIMESTAMP(6),
  ENDRET_AV            VARCHAR2(20),
  VERSJON              NUMBER(11)   NOT NULL,
  OPPRETTET_KILDE_NAVN VARCHAR2(20) NOT NULL,
  K_REFERANSE_T        VARCHAR2(20) NOT NULL,
  JOURNALPOST_ID       NUMBER(11)   NOT NULL,
  ENDRET_KILDE_NAVN    VARCHAR2(20)
) ;

CREATE INDEX XIF1KRYSSREFERANSE
  ON T_KRYSSREFERANSE (K_REFERANSE_T) ;

CREATE INDEX XIF2KRYSSREFERANSE
  ON T_KRYSSREFERANSE (JOURNALPOST_ID) ;

CREATE TABLE T_SAKSRELASJON
(
  SAKSRELASJON_ID      NUMBER(11)   NOT NULL
    CONSTRAINT ISAKSRELASJONU
    PRIMARY KEY,
  SAK_NR_FK            VARCHAR2(20) NOT NULL,
  FEILREGISTRERT       CHAR,
  ENDRET_AV_NAVN       VARCHAR2(50),
  DATO_OPPRETTET       TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV         VARCHAR2(20) NOT NULL,
  DATO_ENDRET          TIMESTAMP(6),
  ENDRET_AV            VARCHAR2(20),
  VERSJON              NUMBER(11)   NOT NULL,
  JOURNALPOST_ID       NUMBER(11)   NOT NULL
    CONSTRAINT T_SAKSRELASJON_R_12
    REFERENCES T_JOURNALPOST,
  K_FAGSYSTEM          VARCHAR2(20) NOT NULL,
  OPPRETTET_KILDE_NAVN VARCHAR2(20) NOT NULL,
  ENDRET_KILDE_NAVN    VARCHAR2(20)
) ;

CREATE INDEX XIE1SAKSRELASJON
  ON T_SAKSRELASJON (SAK_NR_FK) ;

CREATE INDEX XIF2SAKRELASJON
  ON T_SAKSRELASJON (JOURNALPOST_ID) ;

CREATE INDEX XIF3SAKRELASJON
  ON T_SAKSRELASJON (K_FAGSYSTEM) ;

ALTER TABLE T_SAKSRELASJON
  ADD CONSTRAINT T_SAKSRELASJON_R_13
FOREIGN KEY (K_FAGSYSTEM) REFERENCES T_K_FAGSYSTEM ;

CREATE TABLE T_JP_DOK_INFO_REL
(
  JP_DOK_INFO_REL_ID   NUMBER(11)   NOT NULL
    CONSTRAINT XPKJP_DOK_INFO_REL
    PRIMARY KEY,
  TILKNYTTET_AV_NAVN   VARCHAR2(50) NOT NULL,
  DATO_OPPRETTET       TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV         VARCHAR2(20) NOT NULL,
  DATO_ENDRET          TIMESTAMP(6),
  ENDRET_AV            VARCHAR2(20),
  VERSJON              NUMBER(11)   NOT NULL,
  OPPRETTET_KILDE_NAVN VARCHAR2(20) NOT NULL,
  K_TILKN_JP_SOM       VARCHAR2(20) NOT NULL
    CONSTRAINT R_45
    REFERENCES T_K_TILKN_JP_SOM,
  JOURNALPOST_ID       NUMBER(11)   NOT NULL
    CONSTRAINT R_46
    REFERENCES T_JOURNALPOST,
  DOKUMENT_INFO_ID     NUMBER(11)   NOT NULL
    CONSTRAINT R_47
    REFERENCES T_DOKUMENT_INFO,
  ENDRET_KILDE_NAVN    VARCHAR2(20)
) ;

CREATE INDEX XIF4JP_DOK_INFO_REL
  ON T_JP_DOK_INFO_REL (K_TILKN_JP_SOM, JOURNALPOST_ID, DOKUMENT_INFO_ID) ;

CREATE INDEX XIF2JP_DOK_INFO_REL
  ON T_JP_DOK_INFO_REL (JOURNALPOST_ID) ;

CREATE INDEX XIF3JP_DOK_INFO_REL
  ON T_JP_DOK_INFO_REL (DOKUMENT_INFO_ID) ;

CREATE TABLE T_FIL_DETALJER
(
  FIL_DETALJER_ID       NUMBER(11)   NOT NULL
    CONSTRAINT XPKFIL_DETALJER
    PRIMARY KEY,
  DOKUMENT_INFO_ID      NUMBER(11)   NOT NULL
    CONSTRAINT T_FIL_DETALJER_R_16
    REFERENCES T_DOKUMENT_INFO,
  K_FIL_T               VARCHAR2(20) NOT NULL,
  FIL_UUID              VARCHAR2(36) NOT NULL
    CONSTRAINT XAK1FIL_DETALJER
    UNIQUE,
  DATO_ENDRET           TIMESTAMP(6),
  DATO_OPPRETTET        TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV          VARCHAR2(20) NOT NULL,
  ENDRET_AV             VARCHAR2(20),
  ON_DEMAND_ID_FK       VARCHAR2(50),
  K_ONDEMAND_INST       VARCHAR2(20),
  FIL_NAVN              VARCHAR2(200),
  BATCH_NAVN            VARCHAR2(200),
  FIL_STORRELSE         NUMBER(11),
  VERSJON               NUMBER(11)   NOT NULL,
  OPPRETTET_KILDE_NAVN  VARCHAR2(20) NOT NULL,
  K_VARIANT_FORMAT      VARCHAR2(20) NOT NULL
    CONSTRAINT T_FIL_DETALJER_R_49
    REFERENCES T_K_VARIANT_FORMAT,
  ENDRET_KILDE_NAVN     VARCHAR2(20),
  METAFORCE_INSTANCE_ID NUMBER(11)
) ;

CREATE INDEX XIF2FIL_DETALJER
  ON T_FIL_DETALJER (DOKUMENT_INFO_ID) ;

CREATE INDEX XIF1FIL_DETALJER
  ON T_FIL_DETALJER (K_FIL_T) ;

CREATE INDEX ON_DEMAND_ID_FK_IDX
  ON T_FIL_DETALJER (ON_DEMAND_ID_FK) ;

CREATE INDEX XIF3FIL_DETALJER
  ON T_FIL_DETALJER (K_ONDEMAND_INST) ;

CREATE INDEX XIE1FIL_DETALJER
  ON T_FIL_DETALJER (FIL_NAVN) ;

CREATE INDEX XIE2FIL_DETALJER
  ON T_FIL_DETALJER (BATCH_NAVN) ;

CREATE INDEX XIF5FIL_DETALJER
  ON T_FIL_DETALJER (K_VARIANT_FORMAT, DOKUMENT_INFO_ID) ;

ALTER TABLE T_FIL_DETALJER
  ADD CONSTRAINT T_FIL_DETALJER_R_48
FOREIGN KEY (K_ONDEMAND_INST) REFERENCES T_K_ONDEMAND_INST ;

ALTER TABLE T_FIL_DETALJER
  ADD CONSTRAINT T_FIL_DETALJER_R_15
FOREIGN KEY (K_FIL_T) REFERENCES T_K_FIL_T ;

CREATE TABLE T_INNLASTING_JP
(
  INNLASTING_JP_ID NUMBER(11)   NOT NULL
    CONSTRAINT XPKINNLASTING_JP
    PRIMARY KEY,
  FIL_ID_FK        VARCHAR2(200),
  STATUS           VARCHAR2(20),
  RECORD           VARCHAR2(1500),
  FEILMELDING      VARCHAR2(500),
  DATO_OPPRETTET   TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV     VARCHAR2(20) NOT NULL,
  DATO_ENDRET      TIMESTAMP(6),
  ENDRET_AV        VARCHAR2(20),
  VERSJON          NUMBER(11)   NOT NULL
) ;

CREATE INDEX XIE1INNLASTING_JP
  ON T_INNLASTING_JP (STATUS) ;

CREATE TABLE T_SKANNET_INNHOLD
(
  SKANNET_INNHOLD_ID   NUMBER(11)    NOT NULL
    CONSTRAINT ISKANNETINNHOLDU
    PRIMARY KEY,
  VEDLEGG_NR           NUMBER(11),
  VEDLEGG_INNHOLD      VARCHAR2(550) NOT NULL,
  DATO_OPPRETTET       TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV         VARCHAR2(20)  NOT NULL,
  DATO_ENDRET          TIMESTAMP(6),
  ENDRET_AV            VARCHAR2(20),
  VERSJON              NUMBER(11)    NOT NULL,
  DOKUMENT_INFO_ID     NUMBER(11)    NOT NULL
    CONSTRAINT SKANNET_INNHOLD_R_14
    REFERENCES T_DOKUMENT_INFO,
  OPPRETTET_KILDE_NAVN VARCHAR2(20)  NOT NULL,
  ENDRET_KILDE_NAVN    VARCHAR2(20)
) ;

CREATE INDEX XIF1SKANNETINNHOLD
  ON T_SKANNET_INNHOLD (DOKUMENT_INFO_ID) ;

CREATE TABLE T_DOKUMENT_FIL
(
  DOKUMENT_FIL_ID      NUMBER(11)                              NOT NULL
    CONSTRAINT XPKDOKUMENT_FIL
    PRIMARY KEY,
  FIL_UUID             VARCHAR2(36)                            NOT NULL
    CONSTRAINT XAK1DOKUMENT_FIL
    UNIQUE,
  FIL                  BLOB                                    NOT NULL,
  DATO_OPPRETTET       TIMESTAMP(6)                            NOT NULL,
  OPPRETTET_AV         VARCHAR2(20)                            NOT NULL,
  DATO_ENDRET          TIMESTAMP(6),
  ENDRET_AV            VARCHAR2(20),
  VERSJON              NUMBER(11)                              NOT NULL,
  OPPRETTET_KILDE_NAVN VARCHAR2(20) DEFAULT 'KONVERTERT_FELT'  NOT NULL,
  ENDRET_KILDE_NAVN    VARCHAR2(20)
) ;

CREATE TABLE T_BIDRAG_MELLOMLAGRING_DOK
(
  BIDRAG_MELLOMLAGRING_DOK_ID NUMBER(11)   NOT NULL
    CONSTRAINT XPKT_BIDRAG_MELLOMLAGRING_DOK
    PRIMARY KEY,
  DOKUMENT_TYPE               VARCHAR2(20) NOT NULL,
  DOKUMENT                    BLOB         NOT NULL,
  BIDRAG_MELLOMLAGRING_ID     NUMBER(8)    NOT NULL
    CONSTRAINT R_65
    REFERENCES T_BIDRAG_MELLOMLAGRING,
  DATO_OPPRETTET              TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV                VARCHAR2(20) NOT NULL,
  DATO_ENDRET                 TIMESTAMP(6),
  ENDRET_AV                   VARCHAR2(20),
  VERSJON                     NUMBER(11)   NOT NULL
) ;

CREATE TABLE T_DOK_URL_INFO
(
  DOK_URL_INFO_ID NUMBER(11)   NOT NULL
    CONSTRAINT XPKDOK_URL_INFO
    PRIMARY KEY,
  JOURNALPOST_ID  NUMBER(11)   NOT NULL
    CONSTRAINT RELATIONSHIP_1059
    REFERENCES T_JOURNALPOST,
  DOCTOKEN        VARCHAR2(36) NOT NULL
    CONSTRAINT XAK1DOK_URL_INFO
    UNIQUE,
  TIDSPUNKT       TIMESTAMP(6) NOT NULL,
  DATO_OPPRETTET  TIMESTAMP(6) NOT NULL,
  OPPRETTET_AV    VARCHAR2(20) NOT NULL,
  DATO_ENDRET     TIMESTAMP(6),
  ENDRET_AV       VARCHAR2(20),
  VERSJON         NUMBER(11)   NOT NULL,
  FIL_UUID        VARCHAR2(36) NOT NULL,
  TTL_MINUTES     NUMBER(11)
) ;

CREATE INDEX XIF1DOK_URL_INFO
  ON T_DOK_URL_INFO (JOURNALPOST_ID) ;

CREATE SEQUENCE T_FIL_DETALJER_SEQ
CACHE 30 ;

CREATE SEQUENCE T_RETUR_INFO_SEQ
CACHE 30 ;

CREATE SEQUENCE T_DOK_URL_INFO_SEQ
CACHE 30 ;

CREATE SEQUENCE T_DOKUMENT_FIL_SEQ
CACHE 30 ;

CREATE SEQUENCE T_INNLASTING_JP_SEQ
CACHE 30 ;

CREATE SEQUENCE T_KRYSSREFERANSE_SEQ
CACHE 30 ;

CREATE SEQUENCE T_DUMMY_DOKUMENT_SEQ
CACHE 30 ;

CREATE SEQUENCE T_DOKUMENT_INFO_SEQ
CACHE 30 ;

CREATE SEQUENCE T_SKANNET_INNHOLD_SEQ
CACHE 30 ;

CREATE SEQUENCE T_BIDRAG_MELLOMLAGRING_DOK_SEQ
CACHE 30 ;

CREATE SEQUENCE T_SAKSRELASJON_SEQ
CACHE 30 ;

CREATE SEQUENCE T_BIDRAG_MELLOMLAGRING_SEQ
CACHE 30 ;

CREATE SEQUENCE T_JP_DOK_INFO_REL_SEQ
CACHE 30 ;

CREATE SEQUENCE T_JOURNALPOST_SEQ
CACHE 30 ;

CREATE SEQUENCE T_BRUKER_SEQ
CACHE 30;
