CREATE SEQUENCE T_SLETTEBESTILLING_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE T_SLETTEBESTILLING DROP COLUMN ENDRET_AV_KILDE_NAVN;
ALTER TABLE T_SLETTEBESTILLING DROP COLUMN OPPRETTET_AV_KILDE_NAVN;

ALTER TABLE T_SLETTEBESTILLING ADD OPPRETTET_KILDE_NAVN varchar2(512 char) not null;
ALTER TABLE T_SLETTEBESTILLING ADD ENDRET_KILDE_NAVN varchar2(512 char);
ALTER TABLE T_SLETTEBESTILLING ADD VERSJON number (19);
