CREATE SEQUENCE T_SLETTEBESTILLING_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE T_SLETTEBESTILLING
DROP COLUMN ENDRET_AV_KILDE_NAVN,
DROP COLUMN OPPRETTET_AV_KILDE_NAVN;

ALTER TABLE ADD
    OPPRETTET_KILDE_NAVN varchar2(512 char) not null,
    ENDRET_KILDE_NAVN varchar2(512 char),
    VERSION number (19);
