ALTER TABLE T_DOKUMENT_INFO
	ADD (
	K_SKJERMING_TYPE VARCHAR2(128 CHAR),
	CONSTRAINT FK_DOK_INFO_SKJERMING
	FOREIGN KEY (K_SKJERMING_TYPE)
	REFERENCES T_K_BEGRENSNING_TYPE (BEGRENSNING_TYPE)
	ENABLE );
