update T_DOKUMENT_INFO set K_SKJERMING_TYPE = 'ARK' where DOKUMENT_INFO_ID in (select DOKUMENT_INFO_ID from T_JP_DOK_INFO_REL where K_SKJERMING_TYPE = 'FEIL');

update T_DOKUMENT_INFO set K_SKJERMING_TYPE = 'POL' where DOKUMENT_INFO_ID in (select DOKUMENT_INFO_ID from T_JP_DOK_INFO_REL where K_SKJERMING_TYPE = 'POL');
