create table T_BJOARK016_ARBTB (
	JOURNALPOST_ID NUMBER(11,0) NOT NULL, 
	STATUS VARCHAR2(20 BYTE),
	DATO_OPPRETTET TIMESTAMP (6) NOT NULL, 
	OPPRETTET_AV VARCHAR2(20 BYTE) NOT NULL, 
	DATO_ENDRET TIMESTAMP (6), 
	ENDRET_AV VARCHAR2(20 BYTE)	
);

ALTER TABLE T_BJOARK016_ARBTB
ADD CONSTRAINT XPKBJOARK016ARBTB PRIMARY KEY (JOURNALPOST_ID);