CREATE TABLE T_BJOARK017_ARBTB
(
  BJOARK017_ARBTB_ID NUMBER(11)    NOT NULL
    CONSTRAINT XPKT_BJOARK017_ARBTB
    PRIMARY KEY,
  ON_DEMAND_ID       VARCHAR2(50)  NOT NULL,
  SAK_NR             VARCHAR2(20),
  BRUKER_ID          VARCHAR2(11)  NOT NULL,
  BRUKER_TYPE        VARCHAR2(20)  NOT NULL,
  JOURNALPOST_TYPE   VARCHAR2(20)  NOT NULL,
  FAGOMRADE          VARCHAR2(20)  NOT NULL,
  DATO_JOURNAL       TIMESTAMP(6)  NOT NULL,
  JOURNAL_STATUS     VARCHAR2(20)  NOT NULL,
  INNHOLD            VARCHAR2(500) NOT NULL,
  MOTTAKER_NAVN      VARCHAR2(200),
  MOTTAKER_ID        VARCHAR2(20),
  JOURNALF_ENHET     VARCHAR2(20)  NOT NULL,
  DATO_SENDT_PRINT   TIMESTAMP(6),
  OPPRETTET_AV_NAVN  VARCHAR2(50)  NOT NULL,
  DOKUMENT_KATEGORI  VARCHAR2(20)  NOT NULL,
  DATO_DOK_FERDIG    TIMESTAMP(6)  NOT NULL,
  BREVKODE           VARCHAR2(50)  NOT NULL,
  SENSITIVT          CHAR          NOT NULL,
  INNSKR_PARTSINNSYN CHAR,
  FIL_ID_FK          VARCHAR2(200) NOT NULL,
  STATUS             VARCHAR2(20)  NOT NULL,
  FEILMELDING        VARCHAR2(500),
  VERSJON            NUMBER(11)    NOT NULL,
  DATO_OPPRETTET     TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV       VARCHAR2(20)  NOT NULL,
  DATO_ENDRET        TIMESTAMP(6),
  ENDRET_AV          VARCHAR2(20),
  DOKUMENT           BLOB,
  GSAK_SAK_NR        VARCHAR2(20),
  JOURNALPOST_ID     NUMBER(11),
  DOKUMENT_INFO_ID   NUMBER(11),
  UTSENDINGSKANAL    VARCHAR2(20)
);

CREATE TABLE T_BJOARK017_ARBTB_AVSTEMMING
(
  bjoark017_arbtb_avst_id NUMBER(11)    NOT NULL
    CONSTRAINT XPKT_BJOARK017_ARBTB_AVST
    PRIMARY KEY,
  STATUS             VARCHAR2(20)  NOT NULL,
  ON_DEMAND_ID       VARCHAR2(50)  NOT NULL,
  FILNAVN            VARCHAR2(200) NOT NULL,
  VERSJON            NUMBER(11)    NOT NULL,
  DATO_OPPRETTET     TIMESTAMP(6)  NOT NULL,
  OPPRETTET_AV       VARCHAR2(20)  NOT NULL,
  DATO_ENDRET        TIMESTAMP(6),
  ENDRET_AV          VARCHAR2(20)
);

create sequence T_BJOARK017_ARBTB_SEQ;

create sequence T_BJOARK017_ARBTB_AVSTEMMING_SEQ;
