create table T_K_BEGRENSNING_TYPE (
	BEGRENSNING_TYPE VARCHAR2(50) NOT NULL
	CONSTRAINT XPKT_T_K_BEGRENSNING_TYPE
    PRIMARY KEY,
  BEGRENSNING_BESKRIVELSE VARCHAR2(500) NOT NULL,
	DATO_FOM DATE NOT NULL,
	DATO_TOM DATE,
	ER_GYLDIG CHAR(1) NOT NULL,
	OPPRETTET_KILDE_NAVN  VARCHAR2(20) NOT NULL,
	ENDRET_KILDE_NAVN VARCHAR2(20) NOT NULL,
  VERSJON NUMBER(11) NOT NULL,
	DATO_OPPRETTET TIMESTAMP (6) NOT NULL,
	OPPRETTET_AV VARCHAR2(20) NOT NULL,
	DATO_ENDRET TIMESTAMP (6),
	ENDRET_AV VARCHAR2(20)
);

create table T_BEGRENSNING (
  BEGRENSNING_ID NUMBER(11) NOT NULL
    CONSTRAINT XPKT_T_BEGRENSNING
    PRIMARY KEY,
	JOURNALPOST_ID NUMBER(11,0),
	DOKUMENT_INFO_ID NUMBER(11,0),
	BEGRENSNING_TYPE VARCHAR2(50) NOT NULL,
	OPPRETTET_KILDE_NAVN  VARCHAR2(20) NOT NULL,
	ENDRET_KILDE_NAVN VARCHAR2(20) NOT NULL,
  VERSJON NUMBER(11) NOT NULL,
	DATO_OPPRETTET TIMESTAMP (6) NOT NULL,
	OPPRETTET_AV VARCHAR2(20) NOT NULL,
	DATO_ENDRET TIMESTAMP (6),
	ENDRET_AV VARCHAR2(20 BYTE)
);

ALTER  TABLE T_BEGRENSNING
  ADD CONSTRAINT T_BEGRENSNING_TYPE_FK
FOREIGN KEY (BEGRENSNING_TYPE) REFERENCES T_K_BEGRENSNING_TYPE;

ALTER  TABLE T_BEGRENSNING
  ADD CONSTRAINT T_BEGRENSNING_JP_FK
FOREIGN KEY (JOURNALPOST_ID) REFERENCES T_JOURNALPOST;

ALTER  TABLE T_BEGRENSNING
  ADD CONSTRAINT T_BEGRENSNING_DOKINFO_FK
FOREIGN KEY (DOKUMENT_INFO_ID) REFERENCES T_DOKUMENT_INFO;

create sequence T_BEGRENSNING_ID_SEQ;
