--To Journalposter 374808399 og 374681889 har hoveddokumenter som er slettet i prod
INSERT INTO JOARK.T_BEGRENSNING (BEGRENSNING_ID, JOURNALPOST_ID, DOKUMENT_INFO_ID, K_VARIANT_FORMAT, BEGRENSNING_TYPE, OPPRETTET_KILDE_NAVN, OPPRETTET_AV, DATO_OPPRETTET, VERSJON)
SELECT JOARK.T_BEGRENSNING_ID_SEQ.NEXTVAL, JOURNALPOST_ID, NULL, NULL, 'UTILGJENGELIGGJORT','Migrert av MMA-1222','Migrert av MMA-1222',SYSDATE,VERSJON
FROM JOARK.T_JP_DOK_INFO_REL
WHERE DOKUMENT_INFO_ID IN (
  SELECT DOKUMENT_INFO_ID FROM JOARK.T_DOKUMENT_INFO
  WHERE SLETTET = 'T');

ALTER TABLE T_DOKUMENT_INFO
DROP COLUMN SLETTET;

ALTER TABLE T_DOKUMENT_INFO
DROP COLUMN KONFIDENSIALITET;

ALTER TABLE T_DOKUMENT_INFO
DROP COLUMN INTEGRITET;

ALTER TABLE T_DOKUMENT_INFO
DROP COLUMN TILGJENGELIGHET;


