--To Journalposter 374808399 og 374681889 har hoveddokumenter som er slettet i prod
UPDATE T_JOURNALPOST
SET K_SKJERMING_TYPE = 'POL'
where JOURNALPOST_ID IN (
SELECT JOURNALPOST_ID
FROM JOARK.T_JP_DOK_INFO_REL
WHERE DOKUMENT_INFO_ID IN (
  SELECT DOKUMENT_INFO_ID FROM JOARK.T_DOKUMENT_INFO
  WHERE SLETTET = 'T')
);

/*ALTER TABLE T_DOKUMENT_INFO
DROP COLUMN SLETTET;

ALTER TABLE T_DOKUMENT_INFO
DROP COLUMN KONFIDENSIALITET;

ALTER TABLE T_DOKUMENT_INFO
DROP COLUMN INTEGRITET;

ALTER TABLE T_DOKUMENT_INFO
DROP COLUMN TILGJENGELIGHET;
*/

