ALTER TABLE T_JOURNALPOST
ADD
(BEGRENSNING_TYPE VARCHAR2(50));

ALTER TABLE T_FIL_DETALJER
ADD
(BEGRENSNING_TYPE VARCHAR2(50));

ALTER TABLE T_JP_DOK_INFO_REL
ADD
(BEGRENSNING_TYPE VARCHAR2(50));

ALTER  TABLE T_JOURNALPOST
  ADD CONSTRAINT T_JP_BEGRENSNING_TYPE_FK
FOREIGN KEY (BEGRENSNING_TYPE) REFERENCES T_K_BEGRENSNING_TYPE;

ALTER  TABLE T_FIL_DETALJER
  ADD CONSTRAINT T_FILDET_BEGRENSNING_TYPE_FK
FOREIGN KEY (BEGRENSNING_TYPE) REFERENCES T_K_BEGRENSNING_TYPE;

ALTER  TABLE T_JP_DOK_INFO_REL
  ADD CONSTRAINT T_JP_DOK_REL_BEGR_TYPE_FK
FOREIGN KEY (BEGRENSNING_TYPE) REFERENCES T_K_BEGRENSNING_TYPE;

INSERT INTO T_K_BEGRENSNING_TYPE (BEGRENSNING_TYPE, BEGRENSNING_BESKRIVELSE, DATO_OPPRETTET, OPPRETTET_AV)
VALUES ('POL','Begrenset med hjemmel i Personopplysningsloven',sysdate, 'Ketill Fenne');