create table T_K_BEGRENSNING_TYPE (
	BEGRENSNING_TYPE VARCHAR2(50) NOT NULL
	CONSTRAINT XPKT_T_K_BEGRENSNING_TYPE
    PRIMARY KEY,
  BEGRENSNING_BESKRIVELSE VARCHAR2(500) NOT NULL,
	DATO_OPPRETTET TIMESTAMP (6) NOT NULL,
	OPPRETTET_AV VARCHAR2(20) NOT NULL,
	DATO_ENDRET TIMESTAMP (6),
	ENDRET_AV VARCHAR2(20)
);

create table T_BEGRENSNING (
  BEGRENSNING_ID NUMBER(11) NOT NULL
    CONSTRAINT XPKT_T_BEGRENSNING
    PRIMARY KEY,
	JOURNALPOST_ID NUMBER(11) NOT NULL,
	DOKUMENT_INFO_ID NUMBER(11),
	BEGRENSNING_TYPE VARCHAR2(50) NOT NULL,
	K_VARIANT_FORMAT VARCHAR2(20),
	OPPRETTET_KILDE_NAVN  VARCHAR2(20) NOT NULL,
	ENDRET_KILDE_NAVN VARCHAR2(20),
  VERSJON NUMBER(11) NOT NULL,
	DATO_OPPRETTET TIMESTAMP (6) NOT NULL,
	OPPRETTET_AV VARCHAR2(20) NOT NULL,
	DATO_ENDRET TIMESTAMP (6),
	ENDRET_AV VARCHAR2(20)
);

ALTER  TABLE T_BEGRENSNING
  ADD CONSTRAINT T_BEGRENSNING_TYPE_FK
FOREIGN KEY (BEGRENSNING_TYPE) REFERENCES T_K_BEGRENSNING_TYPE;

ALTER  TABLE T_BEGRENSNING
  ADD CONSTRAINT T_BEGRENSNING_JP_FK
FOREIGN KEY (JOURNALPOST_ID) REFERENCES T_JOURNALPOST;

ALTER  TABLE T_BEGRENSNING
  ADD CONSTRAINT T_BEGRENSNING_DOKINFO_FK
FOREIGN KEY (DOKUMENT_INFO_ID) REFERENCES T_DOKUMENT_INFO;

ALTER  TABLE T_BEGRENSNING
  ADD CONSTRAINT T_BEGRENSNING_VARIANT_FK
FOREIGN KEY (K_VARIANT_FORMAT) REFERENCES T_K_VARIANT_FORMAT;

CREATE SEQUENCE T_BEGRENSNING_ID_SEQ;

INSERT INTO T_K_BEGRENSNING_TYPE (BEGRENSNING_TYPE, BEGRENSNING_BESKRIVELSE, DATO_OPPRETTET, OPPRETTET_AV)
VALUES ('UTILGJENGELIGGJORT','Utilgjengelig for saksbehandling uten privilegier',sysdate, 'Ketill Fenne');

CREATE INDEX XIF1BEGRENSNING ON T_BEGRENSNING (BEGRENSNING_TYPE, JOURNALPOST_ID);

CREATE INDEX XIF2BEGRENSNING ON T_BEGRENSNING (BEGRENSNING_TYPE, JOURNALPOST_ID, DOKUMENT_INFO_ID);
