ALTER TABLE T_AKSJONSLOGG
ADD arkivsaksnummer VARCHAR2(50 CHAR);

ALTER TABLE  T_AKSJONSLOGG
ADD arkivsaksystem VARCHAR2(50 CHAR);

ALTER TABLE T_AKSJONSLOGG
  ADD CONSTRAINT T_JP_ARKIVSAKSYSTEM_FK
FOREIGN KEY (arkivsaksystem) REFERENCES T_K_FAGSYSTEM ;