INSERT INTO T_K_AKSJON_TYPE (AKSJON_TYPE, BESKRIVELSE, DATO_OPPRETTET, OPPRETTET_AV)
VALUES ('KOPIER_JOURNALPOST', 'Kopier journalpost', sysdate, 'Bjørnar Hunshamar');

INSERT INTO T_K_AKSJON_TYPE (AKSJON_TYPE, BESKRIVELSE, DATO_OPPRETTET, OPPRETTET_AV)
VALUES ('FEILREGISTRER_SAKSTILKNYTNING', 'Feilregistrer sakstilknytning ', sysdate, 'Bjørnar Hunshamar');

INSERT INTO T_K_AKSJON_TYPE (AKSJON_TYPE, BESKRIVELSE, DATO_OPPRETTET, OPPRETTET_AV)
VALUES ('OPPHEV_FEILREGISTRERING', 'Opphev feilregistrering', sysdate, 'Bjørnar Hunshamar');

INSERT INTO T_K_AKSJON_TYPE (AKSJON_TYPE, BESKRIVELSE, DATO_OPPRETTET, OPPRETTET_AV)
VALUES ('UKJENT_BRUKER', 'Ukjent bruker', sysdate, 'Bjørnar Hunshamar');

INSERT INTO T_K_AKSJON_TYPE (AKSJON_TYPE, BESKRIVELSE, DATO_OPPRETTET, OPPRETTET_AV)
VALUES ('AVBRYT', 'Avbryt', sysdate, 'Bjørnar Hunshamar');

