--To Journalposter 374808399 og 374681889 har hoveddokumenter som er slettet i prod
UPDATE T_JOURNALPOST
SET K_SKJERMING_TYPE = 'POL'
where JOURNALPOST_ID = 374808399;

UPDATE T_JOURNALPOST
SET K_SKJERMING_TYPE = 'POL'
where JOURNALPOST_ID = 374681889;

ALTER TABLE T_DOKUMENT_INFO
    SET UNUSED COLUMN SLETTET;
ALTER TABLE T_DOKUMENT_INFO
    SET UNUSED COLUMN KONFIDENSIALITET;
ALTER TABLE T_DOKUMENT_INFO
    SET UNUSED COLUMN INTEGRITET;
ALTER TABLE T_DOKUMENT_INFO
    SET UNUSED COLUMN TILGJENGELIGHET;

DROP TABLE T_BEGRENSNING;