INSERT INTO T_K_AKSJON_TYPE (AKSJON_TYPE, BESKRIVELSE, DATO_OPPRETTET, OPPRETTET_AV)
VALUES ('KOPIER_JOURNALPOST', 'Kopier journalpost', sysdate, 'Bjørnar Hunshamar');

UPDATE T_K_AKSJON_TYPE SET AKSJON_TYPE = 'FEILREGISTRER_SAKSTILKNYTNING' WHERE AKSJON_TYPE = 'FEILREGISTRER';