DELETE FROM T_K_FAGOMRADE WHERE K_FAGOMRADE = 'BII';
DELETE FROM T_K_FAGOMRADE WHERE K_FAGOMRADE = 'FS22';
DELETE FROM T_K_FAGOMRADE WHERE K_FAGOMRADE = 'MOT';
DELETE FROM T_K_FAGOMRADE WHERE K_FAGOMRADE = 'OVR';
DELETE FROM T_K_FAGOMRADE WHERE K_FAGOMRADE = 'KLA';
DELETE FROM T_K_FAGOMRADE WHERE K_FAGOMRADE = 'KOM';

DELETE FROM T_K_KATEGORI_T WHERE K_KATEGORI_T = 'SYS_SED';
DELETE FROM T_K_KATEGORI_T WHERE K_KATEGORI_T = 'F';
DELETE FROM T_K_KATEGORI_T WHERE K_KATEGORI_T = 'EP';
DELETE FROM T_K_KATEGORI_T WHERE K_KATEGORI_T = 'E_BLANKETT';
DELETE FROM T_K_KATEGORI_T WHERE K_KATEGORI_T = 'KM';

DELETE FROM T_K_FIL_T WHERE K_FIL_T = 'META';
DELETE FROM T_K_FIL_T WHERE K_FIL_T = 'AFP';
DELETE FROM T_K_FIL_T WHERE K_FIL_T = 'DOC';
DELETE FROM T_K_FIL_T WHERE K_FIL_T = 'DOCX';
DELETE FROM T_K_FIL_T WHERE K_FIL_T = 'XLS';
DELETE FROM T_K_FIL_T WHERE K_FIL_T = 'XLSX';


INSERT INTO T_K_FIL_T (k_fil_t, dekode, dato_fom, dato_tom, er_gyldig, dato_opprettet, opprettet_av, dato_endret, endret_av)
SELECT
       'PNG',
       'PNG',
       DATE '1900-01-01',
       NULL,
       '1',
       TIMESTAMP '2018-05-02 10:00:00',
       'Bjørnar Hunshamar',
       TIMESTAMP '2018-05-02 10:00:00',
       'Bjørnar Hunshamar'
FROM dual
WHERE NOT exists(
            SELECT 1
            FROM T_K_FIL_T
            WHERE k_fil_t = 'PNG');

INSERT INTO T_K_MOTTAKS_KANAL (k_mottaks_kanal,dekode,dato_fom,dato_tom,er_gyldig,dato_opprettet,opprettet_av,dato_endret,endret_av) VALUES ('HELSENETTET','Helsenettet',date '1900-01-01',NULL,'1',timestamp '2019-02-05 10:00:00','Bjørnar Hunshamar',timestamp '2019-02-05 10:00:00','Bjørnar Hunshamar');

DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'PSELV';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'E_POST';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'NETS_PB1400';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'NETS_PB1405';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'NETS_PB1406';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'NETS_PB1407';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'NETS_PB1408';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'NETS_PB1411';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'NETS_PB1412';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'NETS_PB1413';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'NETS_PB1423';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'NETS_PB1431';
DELETE FROM T_K_MOTTAKS_KANAL WHERE K_MOTTAKS_KANAL = 'NETS_PB1441';

INSERT INTO T_K_UTSENDINGS_KANAL (k_utsendings_kanal,dekode,dato_fom,dato_tom,er_gyldig,dato_opprettet,opprettet_av,dato_endret,endret_av) VALUES ('HELSENETTET','Helsenettet',date '1900-01-01',NULL,'1',timestamp '2019-02-05 10:00:00','Bjørnar Hunshamar',sysdate);
INSERT INTO T_K_UTSENDINGS_KANAL (k_utsendings_kanal,dekode,dato_fom,dato_tom,er_gyldig,dato_opprettet,opprettet_av,dato_endret,endret_av) VALUES ('TRYGDERETTEN','Trygderetten',date '1900-01-01',NULL,'1',timestamp '2019-02-05 10:00:00','Bjørnar Hunshamar',sysdate);

DELETE FROM T_K_UTSENDINGS_KANAL WHERE K_UTSENDINGS_KANAL = 'PSELV';
DELETE FROM T_K_UTSENDINGS_KANAL WHERE K_UTSENDINGS_KANAL = 'E_POST';
DELETE FROM T_K_UTSENDINGS_KANAL WHERE K_UTSENDINGS_KANAL = 'ALTINN';

UPDATE T_K_UTSENDINGS_KANAL SET DEKODE = 'Digital postkasse til innbyggere' WHERE K_UTSENDINGS_KANAL = 'SDP';

INSERT INTO T_K_AKSJON_TYPE (AKSJON_TYPE, BESKRIVELSE, DATO_OPPRETTET, OPPRETTET_AV) VALUES ('KOPIER_JOURNALPOST', 'Kopier journalpost', sysdate,'Bjørnar Hunshamar');
INSERT INTO T_K_AKSJON_TYPE (AKSJON_TYPE, BESKRIVELSE, DATO_OPPRETTET, OPPRETTET_AV) VALUES ('TILKNYTT_EKSISTERENDE_DOKUMENT', 'Tilknytt eksisterende dokument', sysdate);

UPDATE T_K_AKSJON_TYPE SET AKSJON_TYPE = 'FEILREGISTRER_SAKSTILKNYTNING' WHERE AKSJON_TYPE = 'FEILREGISTRER';

DELETE FROM T_K_TILKN_JP_SOM WHERE K_TILKN_JP_SOM = 'SAMMENSATT_DOK';

UPDATE T_SAKSRELASJON SET K_FAGSYSTEM = 'FS22' where K_FAGSYSTEM in ('AO01', 'IT01');

DELETE FROM T_K_FAGSYSTEM WHERE K_FAGSYSTEM = 'BID';
DELETE FROM T_K_FAGSYSTEM WHERE K_FAGSYSTEM = 'OVR';
DELETE FROM T_K_FAGSYSTEM WHERE K_FAGSYSTEM = 'MOT';
DELETE FROM T_K_FAGSYSTEM WHERE K_FAGSYSTEM = 'OKO';
DELETE FROM T_K_FAGSYSTEM WHERE K_FAGSYSTEM = 'BII';
DELETE FROM T_K_FAGSYSTEM WHERE K_FAGSYSTEM = 'FS19';
DELETE FROM T_K_FAGSYSTEM WHERE K_FAGSYSTEM = 'AO01';
DELETE FROM T_K_FAGSYSTEM WHERE K_FAGSYSTEM = 'IT01';
DELETE FROM T_K_FAGSYSTEM WHERE K_FAGSYSTEM = 'OB36';

DELETE FROM T_K_REFERANSE_T WHERE K_REFERANSE_T = 'SED_FLYT';
DELETE FROM T_K_REFERANSE_T WHERE K_REFERANSE_T = 'SERIE';
DELETE FROM T_K_REFERANSE_T WHERE K_REFERANSE_T = 'OVERSETTELSE';
DELETE FROM T_K_REFERANSE_T WHERE K_REFERANSE_T = 'ETTERSENDT';
DELETE FROM T_K_REFERANSE_T WHERE K_REFERANSE_T = 'SED_SED';

