ALTER TABLE T_BATCH_JOB_EXECUTION MODIFY EXIT_CODE varchar(2500);
ALTER TABLE T_BATCH_JOB_EXECUTION ADD JOB_CONFIGURATION_LOCATION varchar(2500) DEFAULT NULL;
ALTER TABLE T_BATCH_STEP_EXECUTION MODIFY EXIT_CODE varchar(2500);
