drop table T_BJOARK015_ARBTB;
drop table T_BIDRAG_MELLOMLAGRING_DOK;
drop table T_BIDRAG_MELLOMLAGRING;
drop table T_BJOARK015_LOPENR;
drop sequence T_BIDRAG_MELLOMLAGRING_DOK_SEQ;
drop sequence T_BIDRAG_MELLOMLAGRING_SEQ;
drop sequence T_BJOARK015_ARBTB_SEQ;
