ALTER TABLE SAK
    add (BRUKER_ID VARCHAR(40),
         BRUKER_ID_TYPE VARCHAR(40),
         K_SAK_STATUS VARCHAR(40),
         OPPRETTET_KILDE_NAVN VARCHAR(40),
         ENDRET_AV VARCHAR(40),
         DATO_AVSLUTTET timestamp,
         AVSLUTTET_AV VARCHAR(40),
         AVSLUTTET_KILDE_NAVN VARCHAR(40),
         DATO_KASSERT timestamp,
         DATO_AVLEVERT timestamp,
         DATO_SAK_OPPRETTET timestamp,
         ADMINISTRATIV_ENHET VARCHAR(40),
         SAK_ANSVARLIG VARCHAR(40),
         MERKNAD_OPPRYDDING VARCHAR(40)
        );

