ALTER TABLE SAK
    ADD (BRUKER_ID              VARCHAR(40),
         K_BRUKER_ID_T          VARCHAR(40),
         K_SAK_STATUS           VARCHAR(40),
         OPPRETTET_KILDE_NAVN   VARCHAR(40),
         ENDRET_AV              VARCHAR(40),
         DATO_AVSLUTTET         TIMESTAMP,
         AVSLUTTET_AV           VARCHAR(40),
         AVSLUTTET_KILDE_NAVN   VARCHAR(40),
         DATO_KASSERT           TIMESTAMP,
         DATO_AVLEVERT          TIMESTAMP,
         DATO_SAK_OPPRETTET     TIMESTAMP,
         ADMINISTRATIV_ENHET    VARCHAR(40),
         SAK_ANSVARLIG          VARCHAR(40),
         MERKNAD_OPPRYDDING     VARCHAR(40),
         FOREIGN KEY (K_BRUKER_ID_T) REFERENCES T_K_BRUKER_ID_T (K_BRUKER_ID_T)
        );