ALTER TABLE sak
ADD (K_KASSASJON_STATUS VARCHAR2(128),
    K_AVLEVERING_STATUS VARCHAR2(128));

ALTER TABLE K_KASSASJON_STATUS
RENAME TO T_K_KASSASJON_STATUS;

ALTER  TABLE SAK
    ADD CONSTRAINT FK_KASSASJON_STATUS
    FOREIGN KEY (K_KASSASJON_STATUS) REFERENCES T_K_KASSASJON_STATUS;

ALTER  TABLE SAK
    ADD CONSTRAINT FK_AVLEVERING_STATUS
    FOREIGN KEY (K_AVLEVERING_STATUS) REFERENCES T_K_AVLEVERING_STATUS;