ALTER TABLE K_KASSASJON_STATUS
    RENAME TO T_K_KASSASJON_STATUS;

ALTER TABLE SAK
ADD (K_KASSASJON_STATUS VARCHAR2(128)
    CONSTRAINT FK_KASSASJON_STATUS REFERENCES T_K_KASSASJON_STATUS,
    AVLEVERING_ID NUMBER(10),
    K_AVLEVERING_STATUS VARCHAR2(128)
    CONSTRAINT FK_AVLEVERING_STATUS REFERENCES T_K_AVLEVERING_STATUS);
