insert into T_K_OFFENTLIG_JOURNAL_AVSENDER_MOTTAKER (K_OFFENTLIG_JOURNAL_AVSENDER_MOTTAKER) VALUES ('HURUM BO- OG BEHANDLINGSSENTER');
insert into T_K_OFFENTLIG_JOURNAL_AVSENDER_MOTTAKER (K_OFFENTLIG_JOURNAL_AVSENDER_MOTTAKER) VALUES ('OSLOADVOKATENE');
insert into T_K_OFFENTLIG_JOURNAL_AVSENDER_MOTTAKER (K_OFFENTLIG_JOURNAL_AVSENDER_MOTTAKER) VALUES ('ADVOKATFIRMAET SMEDSRUD AS');